wizardsardine/liana

- .gitignore
- src/bitcoin/d/mod.rs
- src/lib.rs
- tests/README.md
- tests/fixtures.py
- tests/requirements.txt
- tests/test_framework/authproxy.py
- tests/test_framework/bitcoind.py
- tests/test_framework/minisafed.py
- tests/test_framework/revault_network.py
- tests/test_framework/utils.py
- tests/test_misc.py
This adds a Python functional tests framework, taken and adapted from `revaultd`. Since we don't have a JSONRPC interface yet it only contains a single trivial startup functional test... And 2 bug fixes this trivial test uncovered! :)
CI integration is still TODO, but it's not critical at the moment and i don't have the heart of fighting with it at the moment (we require a non-standard `bitcoind`).
> Functional tests framework

- src/descriptors.rs
- src/lib.rs
Eventually this module will contain the routines to create all the descriptors we support. For now it only contains the one for the inheritance descriptor.
> Descriptors creation

- src/lib.rs
It allows the gui to import commands
responses structs.
> Make commands module public

- Cargo.lock
- Cargo.toml
- doc/API.md
- src/commands/mod.rs
- src/commands/utils.rs
- src/database/mod.rs
- src/database/sqlite/mod.rs
- src/database/sqlite/schema.rs
- src/descriptors.rs
- src/jsonrpc/api.rs
- src/jsonrpc/mod.rs
- src/lib.rs
- src/testutils.rs
- tests/fixtures.py
- tests/requirements.txt
- tests/test_framework/minisafed.py
- tests/test_framework/serializations.py
- tests/test_framework/utils.py
- tests/test_rpc.py
Based on #27 this implements listing and deletion of Spend transaction from database. The API was based off revaultd's one and @edouardparis' suggestions in #1. We could be smarter in various places but at the moment we KISS.
> Spend transactions listing and deletion

- gui/Cargo.lock
- gui/src/app/menu.rs
- gui/src/app/mod.rs
- gui/src/app/state/coins.rs
- gui/src/app/state/mod.rs
- gui/src/app/view/coins.rs
- gui/src/app/view/message.rs
- gui/src/app/view/mod.rs
- gui/src/installer/config.rs
- gui/src/installer/step/mod.rs
- gui/src/ui/component/badge.rs
- gui/src/ui/component/button.rs
- gui/src/ui/icon.rs
> Add coins panel

- src/descriptors.rs
- src/jsonrpc/api.rs
- src/jsonrpc/server.rs
- src/lib.rs
Clippy just broke under our feets by enabling more checks and making CI fail...
> Clippy fixes

- src/commands/mod.rs
- src/commands/utils.rs
- src/descriptors.rs
- src/jsonrpc/api.rs
- src/jsonrpc/server.rs
- src/lib.rs
> commands: actually use the change descriptor when creating a Spend

- gui/src/installer/mod.rs
> Delete install target datadir in case of failure

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/app/mod.rs
- gui/src/app/state/coins.rs
- gui/src/app/view/coins.rs
- gui/src/ui/component/collapse.rs
- gui/src/ui/component/mod.rs
- gui/src/ui/icon.rs
> Add check height to coins panel

- src/commands/mod.rs
- src/jsonrpc/api.rs
- tests/test_framework/utils.py
- tests/test_rpc.py
- tests/test_spend.py
It was missing a few things, see the linked issues for details.
Fixes #90.
Fixes #76.
Fixes #33.
> Some tweaks to the Spend transaction creation

- .cirrus.yml
- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- LICENCE
- src/bin/cli.rs
- src/bin/daemon.rs
- src/commands/mod.rs
- src/config.rs
- src/database/mod.rs
- src/database/sqlite/mod.rs
- src/jsonrpc/server.rs
- src/lib.rs
- src/testutils.rs
- tests/README.md
- tests/fixtures.py
- tests/test_chain.py
- tests/test_framework/bitcoind.py
- tests/test_framework/lianad.py
- tests/test_framework/utils.py
- tests/test_misc.py
- tests/test_rpc.py
- tests/test_spend.py
We decided on a new name for this project. Farewell Minisafe, "not a Bitcoin vault".
To avoid conflicts with ongoing work in the GUI i have only made the change on the daemon for now.
Fixes #91
> daemon: rename Minisafe to Liana

- CONTRIBUTING.md
- README.md
- contrib/lianad_config_example.toml
- src/bitcoin/d/mod.rs
- src/lib.rs
- tests/test_framework/utils.py
Starting the documentation effort with those two main files. I'll address both a dedicated document about building the software and another dedicated document about recovering from descriptor backup in a follow-up.
> README.md and CONTRIBUTING.md

- gui/src/app/error.rs
- gui/src/app/view/warning.rs
- gui/src/daemon/embedded.rs
- gui/src/daemon/mod.rs
- gui/src/loader.rs
- gui/src/ui/component/button.rs
- gui/src/ui/component/notification.rs
- gui/src/ui/icon.rs
Refac notification::warning component to use a Collapse instead of Tooltip.
close #134
> Add loader error message

- gui/src/app/state/mod.rs
- gui/src/app/view/home.rs
- gui/src/app/view/spend/detail.rs
- gui/src/ui/icon.rs
this resolve some comments in #50
> Display output and input in collapse component

- gui/Cargo.lock
- gui/src/app/mod.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/spend/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/spend/detail.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/spend/step.rs
- gui/src/daemon/model.rs
> Refac spend steps

- src/bitcoin/d/utils.rs
- src/commands/mod.rs
- src/config.rs
- src/descriptors.rs
- tests/fixtures.py
Small things i noticed while working on #148.
> Some tiny cleanups

- gui/src/app/state/spend/step.rs
It don't think it was blatantly wrong, but neither was it entirely correct. And it was seriously lacking comments explaining what was going on for such a tricky calculation.
In order to make sure it's correct, and make this more code more maintainable (and readable to future contributors), clean it up by using a more obviously-correct approach: a transaction template that is filled with inputs depending on the coins that were selected.
I DID NOT TEST IT!
> gui: cleanup the "amount left to select" calculation

- README.md
- doc/BUILD.md
- doc/TRY.md
This adds instructions for building from source, as well as a guide to quickly try out the software on Signet.
> More documentation

- doc/API.md
- src/commands/mod.rs
- tests/test_chain.py
- tests/test_framework/lianad.py
- tests/test_rpc.py
This removes one inconsistencies. Quickly skimming through the doc i didn't find any other.
Fixes #64.
> commands: remove discrepancy between blockheight and block_height

- gui/src/app/view/spend/step.rs
Feedback from Kevin, it is not clear for the user which units the feerate form requires.
> gui: add sat/vbyte label in feerate form

- src/descriptors.rs
Fixes #149.
Also contains a drive-by fix for the sat size API in the second commit.
> Check for key duplicates when creating a descriptor

- gui/README.md
> gui: cleanup the README.

- gui/Cargo.lock
- gui/src/app/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/main.rs
TODO: bump this branch again, after milestone is done
> gui: bump liana for release

- src/commands/mod.rs
- src/jsonrpc/mod.rs
- tests/test_rpc.py
> Fill in `non_witness_utxo` when creating Spend PSBTs

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/app/error.rs
- gui/src/app/view/warning.rs
- gui/src/daemon/client/jsonrpc.rs
- gui/src/daemon/mod.rs
- gui/src/loader.rs
It is not certain that uds_windows will work so we prefer
to remove it.
> gui: disable daemon jsonrpc client for windows

- gui/Cargo.lock
- gui/src/app/menu.rs
- gui/src/app/mod.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/recovery.rs
- gui/src/app/view/hw.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/recovery.rs
- gui/src/app/view/settings.rs
- gui/src/app/view/spend/detail.rs
- gui/src/daemon/client/mod.rs
- gui/src/daemon/embedded.rs
- gui/src/daemon/mod.rs
- gui/src/ui/icon.rs
> gui: add recovery feature

- doc/TRY.md
Replaced the confusing Recovery section with a detailed Ian Coleman keygen.
> Made it more user friendly. Also, ARCH <3

- doc/BUILD.md
I'm quite sure it does the check for you. So i also removed the extra comment. If i'm doing something wrong plz educate me :D
> just put the whole gpg key

- src/bitcoin/d/mod.rs
- src/bitcoin/d/utils.rs
> Decrease threshold of the bitcoind sync progress

- gui/src/app/state/recovery.rs
- gui/src/app/view/recovery.rs
Recoverable coins are coins that recovery
path is available *next* block
> fix recovery state coins filtering

- .dockerignore
- contrib/docker/Dockerfile
- contrib/docker/build.sh
- contrib/docker/cargo_config.toml
- contrib/docker/docker-build.sh
- gui/src/main.rs
Using Docker for now. I'll add documentation once i've figured out macOS.
> Windows reproducible build

- .dockerignore
- contrib/docker/README.md
- contrib/docker/docker-build.sh
- contrib/docker/macos.Dockerfile
- contrib/docker/macos_cmd.sh
- contrib/docker/windows.Dockerfile
- contrib/docker/windows_cmd.sh
This finishes the work on reproducible build with the last missing cross compilation: macOS. I still need to add a README to this folder. I'll do it in this PR.
> MacOS reproducible build using Docker

- gui/src/app/state/recovery.rs
- gui/src/app/state/spend/detail.rs
- gui/src/app/view/spend/detail.rs
- gui/src/hw.rs
> fix various bugs with hws and spend signing process

- README.md
- doc/TRY.md
Some additions to the documentation that were missing or depending on other things.
> Final doc additions

- gui/src/launcher.rs
- gui/src/main.rs
> fix launcher: exit on close event

- Cargo.lock
- Cargo.toml
Once this PR is merged, gui will have its liana last commit updated and version set to 0.1
> liana: 0.1

- gui/src/app/mod.rs
- gui/src/app/state/spend/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/app/view/spend/step.rs
close #195
close #237 
close #196
> gui: fix spend creation steps

- gui/src/app/view/coins.rs
- gui/src/app/view/home.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/spend/detail.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/spend/step.rs
- gui/src/app/view/util.rs
- gui/src/ui/component/text.rs
> gui: display amount with sats in bold

- gui/src/app/state/coins.rs
> gui: order coins list in coins panel

- gui/src/app/view/recovery.rs
Fix issue #265 + small UX improvements.
I rollbacked _rustfmt_ @edouardparis can you see if it makes ~100changes on your side too ?
> Gui: text and layout of recovery screen fix #265

- contrib/reproducible/guix/build.sh
- contrib/reproducible/guix/guix-build.sh
- contrib/reproducible/guix/manifest.scm
> contrib: also patchelf the 'liana-cli' binary

- .github/workflows/main.yml
- contrib/reproducible/guix/guix-build.sh
- contrib/reproducible/guix/manifest.scm
- contrib/reproducible/guix/patches/gui/iced_default_enum.patch
The Iced dependency was updated, and the patch wasn't valid anymore.
> contrib: update the Iced patch for reproducible builds

- gui/Cargo.lock
- gui/src/app/state/settings.rs
- gui/src/app/view/settings.rs
- gui/src/lib.rs
> Add liana version in gui settings

- src/bitcoin/d/mod.rs
- src/lib.rs
> Perform the bitcoind version sanity check before loading the watchonly wallet

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/app/state/spend/detail.rs
- gui/src/app/view/hw.rs
- gui/src/app/view/spend/detail.rs
- gui/src/hw.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> Change HardwareWallet for (Un)Supported enum

- gui/src/installer/prompt.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> Add more information and checkbox to register descriptor step

- gui/src/app/state/recovery.rs
- gui/src/app/state/spend/step.rs
Use this nice helper from rust-bitcoin, instead
of wrong checks.
> fix gui: use address.is_valid_for_network

- src/bitcoin/d/mod.rs
- tests/test_misc.py
What if miners use Liana! :grin:
> bitcoind: detect deposits from (mature) coinbase transactions

- gui/src/app/view/recovery.rs
- gui/src/app/view/spend/step.rs
- gui/src/installer/view.rs
Some things i noticed while testing. Not perfect nor comprehensive, but still an improvement IMO.
> Gui wording nits

- gui/src/app/view/spend/detail.rs
- gui/src/app/view/spend/mod.rs
- gui/src/daemon/model.rs
> gui: change path signature details

- gui/src/installer/view.rs
- gui/src/launcher.rs
- gui/src/main.rs
Gui will do a check that the selected network datadir is correct and will display an error message in case.
> gui: add error message to launcher

- gui/src/app/view/coins.rs
- gui/src/app/view/home.rs
- gui/src/app/view/spend/detail.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/spend/step.rs
- gui/src/daemon/model.rs
- gui/src/ui/component/badge.rs
> Gui unconfirmed badge

- src/commands/mod.rs
- src/commands/utils.rs
- src/jsonrpc/mod.rs
> Transaction creation sanity checks fixes

- gui/src/installer/step/descriptor.rs
> installer: use DescriptorXKey without wildcard

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/hw.rs
> gui: enumerate multiple ledger devices

- README.md
- doc/TRY.md
> doc: some tiny additions to TRY.md

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/app/config.rs
- gui/src/app/mod.rs
- gui/src/app/state/settings.rs
- gui/src/daemon/client/jsonrpc.rs
- gui/src/daemon/client/mod.rs
- gui/src/hw.rs
- gui/src/installer/mod.rs
- gui/src/lib.rs
- gui/src/loader.rs
- gui/src/logger.rs
- gui/src/main.rs
close https://github.com/wizardsardine/liana/issues/338
> Add panic_hook to gui

- gui/src/app/settings.rs
We want to override preexisting settings file.
fixes #383
> gui settings: truncate file

- gui/src/installer/view.rs
- gui/ui/src/component/card.rs
- gui/ui/src/theme.rs
> fix installer pick_list warning

- Cargo.lock
- Cargo.toml
Mostly minor versions as most of the others have broken their MSRV.
> Update our dependencies

- gui/src/installer/step/descriptor.rs
We did not check that the keys in the primary path were using the hot signer. In the case of a hot signing key only used for the primary path,
the hot signer was not advertised to the context
passing to each installer step and was not stored after install.
> fix installer: wrong detection of hot signer usage.

- src/bitcoin/poller/looper.rs
- src/commands/mod.rs
- src/database/mod.rs
- src/database/sqlite/mod.rs
- src/database/sqlite/schema.rs
- src/testutils.rs
This PR aims to resolve #35.
I hope I'm on the right path here. Please let me know in case I need to make further changes.
Thanks.
> lib: couple block height and time

- gui/src/app/state/settings/wallet.rs
- gui/src/app/state/spend/detail.rs
- gui/src/app/view/hw.rs
- gui/src/app/view/settings.rs
- gui/src/app/view/spend/detail.rs
- gui/src/hw.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
- gui/ui/examples/design-system/Cargo.toml
- gui/ui/examples/design-system/src/main.rs
- gui/ui/examples/design-system/src/section.rs
- gui/ui/src/component/hw.rs
- gui/ui/src/component/mod.rs
> Add unregistered policy warning on hw list

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/installer/message.rs
- gui/src/installer/mod.rs
- gui/src/installer/step/mod.rs
- gui/src/installer/view.rs
> gui: check connection to bitcoind in installer

- gui/Cargo.lock
- gui/Cargo.toml
fix the unsupported ledger version `2.1.2-rc`
> bump async-hwi 0.05

- gui/src/app/state/spend/detail.rs
- gui/src/app/view/spend/detail.rs
- gui/src/daemon/model.rs
> gui: display if signer signed in modal

- gui/Cargo.lock
- gui/src/app/menu.rs
- gui/src/app/mod.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/transactions.rs
- gui/src/app/view/coins.rs
- gui/src/app/view/home.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/psbts.rs
- gui/src/app/view/recovery.rs
- gui/src/app/view/spend/detail.rs
- gui/src/app/view/spend/step.rs
- gui/src/app/view/transactions.rs
- gui/src/daemon/model.rs
- gui/ui/Cargo.toml
- gui/ui/examples/design-system/Cargo.toml
- gui/ui/examples/design-system/src/main.rs
- gui/ui/examples/design-system/src/section.rs
- gui/ui/src/component/amount.rs
- gui/ui/src/component/event.rs
- gui/ui/src/component/mod.rs
> Gui new transactions panel

- README.md
It's now outdated after version 0.4 ;)
> README: update the status of the project

- gui/src/app/view/psbts.rs
> fix: psbts list item self-send label

- README.md
preview: https://github.com/edouardparis/liana/tree/add-liana-logo-readme
> Add liana logo to README

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/app/menu.rs
- gui/src/app/mod.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/spend/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/app/view/coins.rs
- gui/src/app/view/home.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/spend/mod.rs
- gui/ui/Cargo.toml
- gui/ui/src/icon.rs
> Add refresh coins buttons

- gui/src/app/view/home.rs
- gui/src/app/view/psbt.rs
- gui/src/app/view/psbts.rs
- gui/src/app/view/recovery.rs
- gui/src/app/view/settings.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/transactions.rs
- gui/ui/src/component/badge.rs
> Some wording cleanups all around the GUI

- gui/src/app/view/recovery.rs
> Change recovery path view when no path is available

- gui/src/app/state/mod.rs
- gui/src/app/view/coins.rs
> Make home warning message relative to timelock

- gui/src/installer/context.rs
- gui/src/installer/message.rs
- gui/src/installer/mod.rs
- gui/src/installer/step/descriptor.rs
This is to resolve #400.
Thanks to @edouardparis for the suggestions and code snippets provided that form the basis of these changes.
I'm opening this PR as draft so you can see my progress and check in case I've missed anything or you'd like some tests added.
Based on my own tests with and without devices, this is working as expected.
> gui: skip register step if no device used

- src/database/sqlite/mod.rs
You can check the unit test triggering the race fails on master. I'm pretty sure it's the reason for the address generation bug i experienced yesterday when testing.
> sqlite: prevent races when updating the next derivation index

- gui/Cargo.lock
- gui/Cargo.toml
> Release 1.0 rc1 of the GUI

- doc/API.md
just rewording minisafe => liana
> doc: replace minisafe by liana

- gui/src/app/view/spend/mod.rs
> gui: minor wording fix

- gui/src/app/view/psbt.rs
- gui/src/app/view/psbts.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/transactions.rs
> minor wording fix

- gui/src/installer/step/descriptor.rs
> gui: clear fingerprint alias when changing device type

- doc/TRY.md
> add tips and tricks

- tests/test_chain.py
Resolves #202 
This PR adds a new test that simulates the typical flow for a user trying to recover their coins
> Add test for rescan and recovery

- src/descriptors/analysis.rs
- src/descriptors/mod.rs
We wouldn't be able to derive them. See https://github.com/wizardsardine/liana/issues/576#issuecomment-1642429179.
> descriptor: refuse non-normalized xpubs

- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> installer: disallow xpub with appended derivation path

- .cirrus.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/hw.rs
- src/bitcoin/d/mod.rs
- src/lib.rs
- tests/test_rpc.py
> GUI: release 1.1

- src/bitcoin/poller/looper.rs
Sleeping for 30 whole seconds impedes the shutdown check. Sleep only .5s but still only do poll bitcoind one every 30s when it's syncing.
It was reported to make the GUI hang when closing it while syncing.
> bitcoin: looper: avoid large sleeps when bitcoind is syncing

- src/bitcoin/d/mod.rs
Props to Kevin for finding this rather significant bug. We should really be catching this type of bugs with code review..
> bitcoind: use the node client to make node requests

- gui/Cargo.lock
> gui: update lianad

- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> check imported descriptor network

- gui/src/app/config.rs
- gui/src/bitcoind.rs
- gui/src/installer/context.rs
- gui/src/installer/mod.rs
- gui/src/installer/step/bitcoind.rs
- gui/src/loader.rs
1. added the bitcoind parent directory
```
.liana/bitcoind
├── bitcoin-25.0
│   └── bin
└── datadir
├── anchors.dat
├── banlist.json
├── bitcoin.conf
├── blocks
├── chainstate
├── debug.log
├── fee_estimates.dat
├── mempool.dat
├── peers.dat
└── settings.json
```
2. change gui config to have `start_internal_bitcoind` : `bool`
> Change gui config and gui internal bitcoind directory architecture

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/main.rs
> gui: use patch for iced_futures

- gui/src/app/state/settings/bitcoind.rs
> backport #691: Allow rescan for external daemon and internal bitcoind

- contrib/release/archlinux/PKGBUILD
> Derive the Arch PKGBUILD from the Debian package.

- gui/Cargo.lock
- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> installer: forbid keys with same master fg in same path

- doc/API.md
- src/commands/mod.rs
- src/database/mod.rs
- src/database/sqlite/mod.rs
- src/jsonrpc/api.rs
- src/testutils.rs
- tests/test_rpc.py
This is an alternative to #735. I believe it's slightly better as it's shorter and does not introduce new allocations. I also addressed my review comments from #735.
> Make it possible to delete labels

- gui/Cargo.lock
- gui/src/app/message.rs
- gui/src/app/state/coins.rs
- gui/src/app/state/label.rs
- gui/src/app/state/psbt.rs
- gui/src/app/state/spend/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/app/view/coins.rs
- gui/src/app/view/home.rs
- gui/src/app/view/label.rs
- gui/src/app/view/message.rs
- gui/src/app/view/psbt.rs
- gui/src/app/view/psbts.rs
- gui/src/app/view/receive.rs
- gui/src/app/view/spend/mod.rs
- gui/src/app/view/transactions.rs
- gui/src/daemon/client/mod.rs
- gui/src/daemon/embedded.rs
- gui/src/daemon/mod.rs
- gui/src/daemon/model.rs
tackle most issues of #732, may need another round of external tries
> Enhance labelling

- gui/src/app/view/label.rs
> Single "Add label" button

- src/bitcoin/d/mod.rs
- src/bitcoin/d/utils.rs
- src/bitcoin/mod.rs
- src/commands/mod.rs
- src/testutils.rs
Fixes https://github.com/wizardsardine/liana/issues/728.
> bitcoind: don't crash on `getblockheader` failure

- src/bin/daemon.rs
address #708  
not sure about wording
> lianad add msg if wrong arg

- gui/src/app/state/psbt.rs
while doing the spend process, a spend transaction and its labels are stored in the database in two case:
* the user clicked on save button
* the user clicked on sign and sign the psbt, triggering the update in database
During the latter, the labels were not updated, which is a bug that makes the user do the whole spending process quickly without storing the labels.
> fix gui: update labels if user signed an unsaved tx

- gui/src/bitcoind.rs
- gui/src/loader.rs
"Forward port" of #770.
It was possible to get into a state where we were waiting for lianad to start, which was waiting on a response from bitcoind which in turn was waiting on the GUI to make room in its piped stdout buffer. Deadlock.
Instead of getting its logs from stdout, read its debug.log file.
> gui: don't read bitcoind's stdout to avoid a deadlock

- gui/src/app/view/psbt.rs
The analysis was wrongly displayed. For instance it could display a fingerprint as having both signed and not signed yet.
Clean up the code and fix the analysis.
> GUI: fix the display of missing signatures in PSBT analysis

- gui/src/app/view/psbt.rs
The analysis was wrongly displayed. For instance it could display a fingerprint as having both signed and not signed yet.
Clean up the code and fix the analysis.
> gui: view: fix the display of PSBT missing signatures

- doc/API.md
- doc/BUILD.md
- doc/TRY.md
> docs: fix typos

- gui/src/launcher.rs
This is to resolve #543.
I've used a trash icon instead of a cross, but can change it to a cross if preferred.
> gui: add option to delete wallet

- gui/src/launcher.rs
- gui/ui/src/theme.rs
> gui: make the trash button prettier

- src/bitcoin/d/mod.rs
> bitcoind: error when trying to rescan past prune height

- gui/src/installer/step/bitcoind.rs
> fix panic for managed bitcoind on network change

- gui/src/app/message.rs
- gui/src/app/state/transactions.rs
> gui: duplicate labels for rbf psbt

- gui/src/app/state/psbt.rs
- gui/src/app/state/settings/wallet.rs
- gui/src/installer/step/descriptor.rs
> gui: do not display hw error on simple user refusal

- gui/src/main.rs
> [GUI] Add version args

- gui/src/app/state/receive.rs
> [GUI] Add index into qrcode

- src/descriptors/keys.rs
This was untested, what could go wrong? Well, it was wrong of course!
> descriptors: fix derived key parsing and formatting

- gui/src/app/cache.rs
- gui/src/app/message.rs
- gui/src/app/mod.rs
- gui/src/app/state/coins.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/psbts.rs
- gui/src/app/state/receive.rs
- gui/src/app/state/recovery.rs
- gui/src/app/state/settings/bitcoind.rs
- gui/src/app/state/settings/mod.rs
- gui/src/app/state/settings/wallet.rs
- gui/src/app/state/spend/mod.rs
- gui/src/app/state/spend/step.rs
- gui/src/app/state/transactions.rs
- gui/src/app/view/message.rs
- gui/src/app/view/mod.rs
- gui/src/app/view/spend/mod.rs
- gui/src/loader.rs
- gui/src/utils/sandbox.rs
This refac keeps each panel state in parallel.
> Refac app: keep every panel states

- doc/API.md
- src/commands/mod.rs
- src/jsonrpc/api.rs
- src/jsonrpc/mod.rs
- tests/test_rpc.py
> Add optional txids param to listspendtxs

- contrib/lianad_config_example.toml
> fix descriptor in config example

- gui/src/main.rs
this PR  introduce handling of new events in all views:
- `Tab` will move cursor to the next TextInput
- `Tab` + `Shift` will move the cursor to previous TextInput
> [GUI] tab on TextInputs

- gui/Cargo.lock
- gui/src/app/mod.rs
- gui/src/daemon/client/mod.rs
- gui/src/daemon/embedded.rs
- gui/src/daemon/mod.rs
- gui/src/installer/mod.rs
- gui/src/loader.rs
> Gui handle poller error

- gui/src/app/state/transactions.rs
> fix transaction update after label change

- gui/src/app/view/spend/mod.rs
This backports https://github.com/wizardsardine/liana/pull/1055.
> 5.0: Backport #1055

- gui/src/bitcoind.rs
> Backport #1064 to 5.0

- src/bin/daemon.rs
> [Daemon] Add -v/--version/-h/--help args 

- README.md
- doc/RELEASE.md
This document a bunch of stuff i've been doing for every release in the past years. I've detailed it in a number of steps for clarity.
Fixes https://github.com/wizardsardine/liana/issues/803.
> Document the release process

- gui/src/app/view/settings.rs
> replace AboutSection -> EditWalletSettings

- gui/ui/src/component/collapse.rs
In a previous PR #1096, we made usage
of the widget state instead of the component state to set the collapsed value when the widget is created. But the widget is reset at each refresh of the interface, instead the component state does not change.
This commit makes the distinction between the two by having the widget state as an initial state and the component one as a capture of the user clicks.
> fix ui: wrong usage of widget state

- doc/USAGE.md
Fixes #1106, taproot support already specified in doc/signing_devices.md
> Update hw support info

- gui/shell.nix
> fix outdated `gui/shell.nix`

- gui/src/main.rs
fixes #506 
i put ~~800x800~~ as default size, feel free to told me if you think something else more appropriate.
edit: i change to 1000x800 so we can also close #507 (i do not have strong opinion, 1000 looks a bit large to me, but if we decide less than 1000 i think we shouls close #507 also)
> Set minimum window size

- gui/src/installer/view.rs
This PR replace the descriptor displayed in the installer descriptor registration step, by the wallet policies template + its keys, as almost (all?) signing devices displays the discriptor in this way for registration.
closes #727
> replace the descriptor by template in descriptor registration step

- .github/workflows/main.yml
- gui/src/app/state/label.rs
- gui/src/app/state/psbt.rs
- gui/src/app/state/settings/wallet.rs
- gui/src/app/state/spend/step.rs
- gui/src/hw.rs
- gui/src/installer/step/bitcoind.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/step/mod.rs
- gui/src/main.rs
- gui/ui/src/component/toast.rs
- src/commands/mod.rs
- src/config.rs
- src/descriptors/mod.rs
- src/jsonrpc/api.rs
Note [this](https://github.com/pythcoiner/liana/blob/7a11fe584a3422502dce8519700dfb05c6f7f937/gui/src/main.rs#L5-L6) is related to a clippy warning that appear on MacOs (and i guess on windows)
> Clippyfy rust 1.78.0

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/hw.rs
> update async-hwi with serial fix

- gui/src/app/state/psbt.rs
- gui/src/daemon/client/mod.rs
first commit is a non regression test, should fail on CI.
close #1133
> gui: fix psbt update

- gui/src/installer/step/bitcoind.rs
- gui/src/installer/view.rs
This PR is a variant of #1137, it add a warning under text input field if user try to connect to a non-loopback address & use RPCAuth:
It also add a check on address + RPC user/password/cookie:
Check connection button is greyed out until address is valid + user and password are filled (if RPCAuth selected)
Closes https://github.com/wizardsardine/liana/issues/1059
> installer: add a warning if remote adress is not loopback

- gui/Cargo.lock
- gui/Cargo.toml
- gui/src/daemon/model.rs
- gui/src/lib.rs
In preparation of the rc1 release.
> gui: bump version to v6

- doc/TRY.md
> Add instruction to refresh Antoine PGP key

- gui/src/app/state/transactions.rs
close #1174 
labels were not updated if tx already exists
> gui: TransactionPanel.update() -> update label if tx already exists

- gui/src/installer/step/descriptor.rs
> installer: reset signing device registration if descriptor change

- gui/src/installer/message.rs
- gui/src/installer/mod.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/step/mod.rs
- gui/src/installer/step/share_xpubs.rs
- gui/src/installer/view.rs
> Remove participate wallet process for share xpubs simple panel

- gui/src/installer/step/share_xpubs.rs
- gui/src/installer/view.rs
Because the share xpubs is not anymore a install process, no information is stored. If user want to generate a new mnemonic and share it xpubs he must be aware that he has to backup it.
close #1203
> Add list of words for new generated mnemonic in share xpubs panel

- gui/src/app/state/spend/step.rs
> gui: in DefineSpend.update() call check_valid() if Coins updated

- src/descriptors/analysis.rs
This PR add a check to verify that the change descriptor is not hardened.
without this check it allow import of invalid (not  derivable change) multipath like <0;1'> into a LianaDescriptor.
closes #1183
> DesKeyChecker.check() => check the change multipath is not hardened

- gui/src/app/view/coins.rs
> fix wrong units in remaining time warning

- gui/src/main.rs
> change min window height to 650

- gui/src/lianalite/client/backend/mod.rs
> Add Liana-Version header to remote backend client

- gui/src/app/state/settings/wallet.rs
- gui/src/app/view/settings.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/view.rs
> Display details of wallet policy in installer

- gui/src/installer/context.rs
- gui/src/installer/message.rs
- gui/src/installer/mod.rs
- gui/src/installer/step/backend.rs
- gui/src/installer/step/descriptor.rs
- gui/src/installer/step/mod.rs
- gui/src/installer/view.rs
From the issue https://github.com/wizardsardine/liana/issues/1240 It was decided to separate the installer step where user choose the backend and the login.
> Separate login from choose backend step

- .cirrus.yml
This adds the spend functional tests to the CI pipeline.
> ci: run spend functional tests

- gui/src/installer/view.rs
- gui/src/launcher.rs
- gui/src/lianalite/login.rs
discussed in #1240 and discord
> Change remote backend wording

- src/bitcoin/electrum/mod.rs
- src/lib.rs
This Michael's last commit from #1285.
> electrum: check in db if rescan required

- gui/src/installer/view.rs
> installer: change liana connect description

- src/bitcoin/electrum/mod.rs
- src/bitcoin/electrum/wallet.rs
Changing values as discussed in #1292.
> electrum: reduce load on server

- gui/src/app/state/settings/bitcoind.rs
- gui/src/installer/step/node/electrum.rs
22ed096 fixes #1306 
2bd22b4 fixes #1305 
fd50913 in order to make clippy happy
> backend settings

- src/bitcoin/poller/looper.rs
For Electrum, we detect reorgs while syncing based on our local chain.
When a user requests a rescan, we roll the DB back to genesis block, but leave the local chain as it is. If there's then a reorg, we would find the common ancestor with respect to our local chain, which would be later than the DB's tip. In order not to miss any updates, we shouldn't roll the DB tip forward in that case.
> electrum: don't roll the tip forward upon reorg

- gui/src/app/view/settings.rs
> fix wrong redirection message in settings

- gui/src/app/view/hw.rs
- gui/src/hw.rs
- gui/src/installer/view.rs
- gui/ui/src/component/hw.rs
> Check coldcard version and request user to upgrade

- SECURITY.md
> doc: fix broken link to Edouard PGP key

- gui/src/lianalite/client/auth.rs
- gui/src/lianalite/login.rs
close https://github.com/wizardsardine/liana/issues/1385
> Fix lianalite resend token

- gui/src/installer/view/editor/mod.rs
> gui(edit key modal): increase size of the closing icon

- gui/src/app/message.rs
- gui/src/app/state/mod.rs
- gui/src/app/state/transactions.rs
- gui/src/app/view/home.rs
- gui/src/app/view/transactions.rs
- gui/src/daemon/model.rs
This is part of a major rework to fix performance issue while loading lot of transactions in the gui.
> Refac pagination: sort list in async command

- gui/src/installer/view/mod.rs
- gui/ui/src/component/hw.rs
> gui(installer): display warning & selected icons

- gui/src/installer/view/mod.rs
> backport for v8: #1442: gui(installer): use fixed keys ordering

- gui/src/installer/view/mod.rs
> backport for v8: #1446: gui(installer): list wallets using secondary buttons

- liana-gui/src/app/view/home.rs
> Use 2 decimal for sync progression in home page

- Cargo.lock
- contrib/reproducible/guix/build.sh
- liana-gui/Cargo.toml
- liana-gui/src/daemon/embedded.rs
- liana-gui/src/installer/mod.rs
We import directly liana with the directory path instead of the git url.
> Update liana gui to import liana directly

- liana-gui/src/app/state/receive.rs
close https://github.com/wizardsardine/liana/issues/1461
Stop generating addresses without user explicitly asking so.
Otherwise, the gap will be too big and some rescan with default gap limit on other wallets will not detect funds.
> gui: stop auto load of address when opening receive panel

- liana-gui/src/export.rs
> export: list transaction in chronological order

- liana-gui/src/app/state/settings/bitcoind.rs
- lianad/src/bitcoin/mod.rs
- lianad/src/database/mod.rs
- lianad/src/database/sqlite/mod.rs
- lianad/src/lib.rs
- tests/test_framework/bitcoind.py
> chore: fix some comments

- Cargo.lock
- liana-gui/Cargo.toml
Bump required to fix a problem with coldcard while fetching xpub
> bump async-hwi 0.0.27

- liana-gui/src/installer/view/editor/template/custom.rs
> gui(installer): widen button to fit text on single line

- liana-gui/src/app/view/transactions.rs
> Add backup icon to transactions export

- Cargo.lock
- lianad/Cargo.toml
> lianad: drop defaults features for bip329 crate

- liana-gui/src/app/view/settings.rs
- liana-ui/src/theme/mod.rs
- liana-ui/src/theme/palette.rs
- liana-ui/src/theme/rule.rs
> gui: reformat Settings > Import/Export view

- liana-gui/src/installer/view/mod.rs
> installer: add a spacer bellow Next button at descriptor registration step

- liana-gui/src/app/view/psbt.rs
> gui: add a spacer below Delete button un PSBT view

- liana-gui/src/app/menu.rs
- liana-gui/src/app/mod.rs
- liana-gui/src/app/state/mod.rs
- liana-gui/src/app/view/home.rs
- liana-gui/src/app/view/message.rs
- liana-gui/src/daemon/mod.rs
- liana-gui/src/loader.rs
- liana-gui/src/main.rs
> show rescan warning after restoring wallet from backup

- liana-gui/src/app/state/export.rs
> gui: rename descriptor export extension *.descriptor => *.txt

- Cargo.lock
> miniscript 12.3.1

- liana-gui/src/app/state/spend/step.rs
- liana-gui/src/app/view/spend/mod.rs
> Show fee next to feerate input when creating a new spend

- liana-ui/src/theme/palette.rs
You can see here the black background for the slider : 
Closes #1670
> Fix sliders background color

- liana-gui/src/app/view/recovery.rs
This fixes and implements the items from #1664, except for the alias refresh, which is covered by #1667.
> Small fixes and improvements to the Recovery panel UI

- liana-gui/src/main.rs
Adding the network flag to liana-gui command opens now the launcher with the network set instead of trying to run the wallet in the network directory.
This is preparatory work for the multiple wallet feature.
> refac liana-gui: network flag redirects to launcher

- tests/README.md
- tests/requirements.txt
Had issues because of a too old version of pytest-timeout. I had to update it so I took advantage of it to update pytest and other requirements
> Upgrade pytest

- liana-gui/src/app/view/coins.rs
- liana-gui/src/app/view/home.rs
- liana-gui/src/app/view/psbt.rs
- liana-gui/src/app/view/receive.rs
- liana-gui/src/app/view/recovery.rs
- liana-gui/src/app/view/settings.rs
- liana-gui/src/app/view/spend/mod.rs
You can see below the updated GUI. If needed I can make the panel's "Broadcast" button secondary when the broadcast modal is displayed.
> gui: review primary buttons in the application

- liana-gui/src/app/settings.rs
- liana-gui/src/app/state/settings/wallet.rs
- liana-gui/src/app/wallet.rs
- liana-gui/src/backup.rs
- liana-gui/src/export.rs
- liana-gui/src/installer/mod.rs
- liana-gui/src/launcher.rs
- liana-gui/src/loader.rs
- liana-gui/src/main.rs
> Advisory lock settings

- liana-gui/src/app/message.rs
- liana-gui/src/app/state/receive.rs
- liana-gui/src/app/view/message.rs
- liana-gui/src/app/view/receive.rs
- liana-gui/src/daemon/client/mod.rs
- liana-gui/src/daemon/embedded.rs
- liana-gui/src/daemon/mod.rs
- liana-gui/src/daemon/model.rs
- liana-gui/src/services/connect/client/backend/api.rs
- liana-gui/src/services/connect/client/backend/mod.rs
- lianad/src/commands/mod.rs
This implements #809 by listing unused addresses on the Receive panel.
> feat: List unused addresses on Receive panel

- liana-gui/src/installer/mod.rs
- liana-gui/src/installer/step/node/bitcoind.rs
This fixes #1708.
There would be no way to get the RPC password of an existing managed bitcoind installation without looking in other daemon.toml files.
An existing rpcauth field in the bitcoin.conf file will remain unchanged so that an existing wallet using username/password authentication will continue to work.
> fix: use cookie file auth for new wallets with managed bitcoind

- doc/RECOVER.md
> doc: update recover.md since Bitcoin 29.0 supports multipath descriptors

- liana-gui/src/launcher.rs
- liana-gui/src/loader.rs
This fixes a couple of checks for whether the wallet uses a managed bitcoind.
> fix checks for whether wallet uses managed bitcoind

- liana-gui/src/installer/message.rs
- liana-gui/src/installer/mod.rs
- liana-gui/src/installer/step/backend.rs
- liana-gui/src/installer/view/mod.rs
- liana-gui/src/services/connect/client/cache.rs
> installer: reuse existing accounts

- liana-gui/src/loader.rs
Fixes #1256.
The loading screen showing the blockchain sync progress will skipped if the node type is not Bitcoin Core.
> fix: skip syncing screen if node is not bitcoind

- liana-gui/src/loader.rs
> fix: change wording loader go back button

- liana-gui/src/app/state/settings/bitcoind.rs
- liana-gui/src/export.rs
- liana-gui/src/installer/view/mod.rs
- liana-gui/src/main.rs
> chore(docs): minor typo fixes

- liana-gui/src/installer/step/descriptor/editor/key.rs
- liana-ui/src/component/modal.rs
> Improve key modal UI

- liana-gui/src/installer/step/descriptor/editor/key.rs
> change version upgrade error message

- liana-gui/src/installer/step/backend.rs
fix message not forwarded to decrypt modal in liana-connect flow
> installer: fix message not forwarded to decrypt modal
