src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/bitcoin/poller/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/lib.rs
This introduces the Bitcoin poller, an event loop in a new thread that continuously poll our Bitcoin backend to update our state. This is kept minimal; only introduce the necessary components (Bitcoin interface, DB interface) and as such it only takes care of updating the best tip at the moment.
=> Bitcoin interface poller

src/bin/daemon.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/lib.rs
This module contains the implementation of our external API. Like the others, it's very inspired (or grossly copied from) `revaultd`.
This PR implements the `getinfo` and `getnewaddress` commands to showcase the usage of the new `DaemonControl` command.
=> Introduce the `commands` module

doc/API.md, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/commands/utils.rs, src/config.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/database/sqlite/utils.rs, src/descriptors.rs, src/jsonrpc/api.rs, src/lib.rs, src/testutils.rs, tests/fixtures.py, tests/test_rpc.py
This introduces types for our inheritance descriptor. This is taken and adapted from revaultd, where it turned out to be very helpful.
This also adds a helper to query the timelock of the heir's spending path in the inheritance descriptor for downstream users to be able to compute the expiration block of each coin.
This is based on #13.
=> Typesafe descriptor management

.cirrus.yml
Taken and adapted from revaultd.
Now that 24.0rc1 of Bitcoin Core is released we can actually have a CI for functional tests.
Fixes #14.
=> ci: add a Cirrus configuration for the functional tests

Cargo.lock, Cargo.toml, doc/API.md, src/commands/mod.rs, src/commands/utils.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/descriptors.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/lib.rs, src/testutils.rs, tests/fixtures.py, tests/requirements.txt, tests/test_framework/minisafed.py, tests/test_framework/serializations.py, tests/test_framework/utils.py, tests/test_rpc.py
This implements two new commands to create and store a Spend transaction PSBT. We'll need a `listspendtxs` and `delspendtx` eventually as in `revaultd`.
This has poor change management (address reuse for simplicity). I was thinking of using odd/even indexes to differentiate receive/change addresses before we have [multi-path descriptors](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-July/020791.html). Now i wonder if it makes sense at all to implement this odd/even thing and just stick with address reuse before multi-paths descriptors. Nobody is supposed to use that anyways.
=> Spend transactions creation and storage

src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/testutils.rs
Add two new columns:
- `blocktime`: timestamp of the block containing the transaction funding the coin.
- `spent_at`: timestamp of the block containing the transaction spending the coin.
Update the coin `spent_at` when the spend transaction is confirmed
=> Check spend status in bitcoin poller

.cirrus.yml, doc/API.md, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/jsonrpc/api.rs, src/testutils.rs, tests/test_chain.py, tests/test_framework/bitcoind.py, tests/test_framework/utils.py, tests/test_rpc.py
This finally implements our reorganization handling. Like in revaultd, upon noticing a tip change that indicates a reorg happened in our Bitcoin backend we rollback our state to the common ancestor between our state and the new chain, then start rescanning from there. The logic is much more straightforward than in revaultd though, as there is no presigned transactions to care about.
The PR grew a bit large as this needed a bit of preparatory work in order to be reasonably tested (and i noticed a few bugs and cleanups that slipped through review in #29). Please let me know if reviewers prefer that i split the prep work on the commands in another PR.
Fixes #15.
=> Chain reorganization handling

doc/API.md, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/commands/mod.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/testutils.rs, tests/test_framework/minisafed.py, tests/test_framework/serializations.py, tests/test_framework/utils.py, tests/test_rpc.py
This implements a new command to broadcast an existing Spend transaction.
Fixes #58.
Fixes #66.
=> A new `broadcastspend` command

.github/workflows/main.yml, Cargo.lock, Cargo.toml, src/commands/mod.rs, src/commands/utils.rs, src/config.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/descriptors.rs, src/testutils.rs, tests/test_rpc.py
Took the opportunity to update some dependencies, too.
=> Update `rust-miniscript` to 8.0.0

Cargo.lock, Cargo.toml, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/bitcoin/poller/mod.rs, src/commands/mod.rs, src/config.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/database/sqlite/utils.rs, src/descriptors.rs, src/lib.rs, src/testutils.rs, tests/fixtures.py, tests/requirements.txt, tests/test_framework/minisafed.py, tests/test_rpc.py, tests/test_spend.py
This fixes #18 by implementing the de-facto standard of using a `/0/*` keychain for receiving addresses and a `/1/*` keychain for change addresses. Note that once we'll have multisig, reusing addresses will still be possible since wallet don't share the same "next derivation index".
In order to avoid forcing the user to configure and backup two almost identical descriptors, we make use of the recently proposed BIP389 (https://github.com/bitcoin/bips/pull/1354). In order to prevent as much as possible introducing a backward incompatibility in the configuration file after the first release, we restrict the usage of multipath descriptors to `<0;1>` here.
We now derive public keys from `xpub/0/*` and `xpub/1/*` while we were previously deriving them from `xpub/*`.
This triggered a pretty …
=> Decent change management (using multipath descriptors)

doc/API.md, src/bitcoin/d/mod.rs, src/bitcoin/d/utils.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/lib.rs, src/testutils.rs, tests/test_chain.py, tests/test_framework/bitcoind.py, tests/test_framework/minisafed.py, tests/test_rpc.py
This implements the ability for a user to rescan the block chain from an earlier timestamp to find transactions the wallet isn't currently aware of.
The main difficulty arises with the fact there are two rescans to be performed:
1. The block chain rescan on the Bitcoin backend. For the bitcoind implementation this means we need to rescan the bitcoind watchonly wallet down to the given timestamp (or height). We can imagine for an indexer backend such as an Electrum backend it could be almost instant.
2. The update of our state with the new state of the Bitcoin backend. In the poller we scan blocks linearly, we will never scan a block that we already scanned and that includes blocks anterior to the first block we scanned. In order to implement this rescan of past blocks after a Bitcoin …
=> Block chain rescanning for our descriptor(s)

src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/utils.rs, src/testutils.rs, tests/test_rpc.py
Currently, we wouldn't update our "next derivation index" to derive receive/change addresses if we noticed an address from a higher derivation index was used onchain. See #81. This fixes it.
Note that it can be tempting to set it with some leeway (for instance if we notice index `n` was used, we set our next derivation index to `n + 10`) since other wallets probably have generated addresses for more addresses than were actually used onchain.
However, i think it could have cascading effects in a multisig situation: A would use `n`, B would set its to `n + 10` and use `n + 11`, C would set its to `n + 21` and use `n + 22`. This is clear that we could end up very far indeed down the derivation tree without having used most indexes.
A functional test is included, demonstrating the behaviour …
=> Derivation index update from the chain

src/bitcoin/d/mod.rs, tests/test_spend.py
There were a couple cases in which we would not detect a coin as spent:
1. If the deposit transaction was still unconfirmed
2. If the spend transaction did not contain any external output
This comes with a functional test that will fail on master. It tests both above cases as well as many other.
Fixes #125
=> Spent coin detection fixes

contrib/coverage.sh
Taken and adapted from revaultd. Can be trivially adapted to the GUI.
=> contrib: add a script to generate coverage data for the daemon

doc/TRY.md
Sigh.. I just copied what was in gui/README.md
=> doc: quicktry: pkg-config isn't a runtime dependency!

.github/workflows/main.yml
So we at least have one MacOS job. Because it looks like #69 isn't going anywhere.
=> ci: re-enable ci on non-1.48 for MacOS

Cargo.toml
This new syntax would actually force all downstream users to apply the patch section in their Cargo.toml! Revert to the previous syntax of specifying the git repo directly.
=> Cargo: fix the rust-miniscript patched dependency for downstream

src/bin/daemon.rs, src/bitcoin/d/mod.rs, src/lib.rs
We were not properly treating warming up errors when bitcoind was starting up. Also, better to just log as error and `exit` with `1` instead of panic'ing on a daemon startup error.
See the commit messages for details.
Fixes #134 
Fixes #163
=> Friendlier bitcoind startup error handling

gui/Cargo.lock
This version of the client contains a fix
required for the no inputs recognized warning.
=> gui: bump ledger_bitcoin_client 0.1.1

gui/src/app/state/mod.rs, gui/src/app/view/home.rs
Because pending events are in a different list
that confirmed event. The wrong list item was
selected when user tried to click on a pending
event.
=> fix gui: wrong event selection on home panel

doc/API.md, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/descriptors.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/testutils.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_framework/utils.py, tests/test_rpc.py
A new command that provides a simple way for a user to sweep all the coins whose timelocked recovery path is available.
The first part of #180. Note this also contains a number of drive-by fixes that i noticed while coding this up.
=> Recovery command to sweep "expired" coins

gui/src/app/view/coins.rs, gui/src/app/view/spend/step.rs
Add remaining timelock and unconfirmed label.
close #232
=> fix inconsistencies between spend and coins panel

gui/src/app/state/spend/step.rs, gui/src/app/view/spend/detail.rs, gui/src/daemon/mod.rs, gui/src/daemon/model.rs
Use the presence of bip32_derivation
in the spend outputs to detect the
change outputs.
=> fix spend change detection

doc/API.md, src/commands/mod.rs, src/commands/utils.rs, tests/test_rpc.py
Multiple change indexes may be present in a spend
draft transaction and can be detected instead
in the response psbt with the bip32_derivation
outputs fields.
=> Remove change_index from listspendtxs response

contrib/release/release.sh
It would create an empty archive since it didn't recurse down the directories..
=> contrib: fix windows archive creation in release script

gui/Cargo.lock, gui/Cargo.toml
The version of the iced crates are
upgraded without introducing version
change in the other external dependencies.
This upgrade introduces fixes of the iced
framework. See:
https://github.com/iced-rs/iced/releases/tag/0.6.0
=> gui: bump iced 0.6

gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/state/recovery.rs, gui/src/app/state/settings.rs, gui/src/app/state/spend/detail.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs, gui/src/app/wallet.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/loader.rs, gui/src/main.rs, gui/src/utils/mock.rs
A new module wallet is introduced that contains the main_descriptor retrieved from `getinfo`.
It removes the requirement for the `Daemon` trait to provide the demon config in the  other components of the application.
Actually BitcoindSettings cannot be edited if the gui is connected to an external daemon, this PR just remove the display of the Bitcoind Settings section.
=> gui: store descriptor in wallet module

src/descriptors.rs, src/testutils.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_framework/signer.py, tests/test_framework/utils.py, tests/test_misc.py, tests/test_rpc.py, tests/test_spend.py
This permits the creation of a Liana descriptor containing a multisig in either of the two spending paths. The multisig is currently restricted at creation time to be a CHECKUMULTISIG-like multisig (k-of-n with n<20). See the linked issue for rationale.
Closes https://github.com/wizardsardine/liana/issues/53.
=> Multisig support

src/config.rs, src/database/sqlite/mod.rs, src/descriptors.rs, src/lib.rs, src/testutils.rs, tests/fixtures.py
It would be possible for users to create a descriptor with xpubs without an origin set. In fact, not many are used to origins and it's a very likely mistake. Signers need this information in order to be able to sign. So they could potentially create a wallet and potentially never be able to sign for one or multiple keys.
Fix this by requiring an origin for all keys in the descriptor.
Fixes #290.
=> descriptors: require that an origin be set for the keys.

gui/src/main.rs
ledger hid apdu exchanges were displayed in the log because of ledger_transport_hid crate.
This commit removes these log entries.
=> gui: log off ledger_transport_hid

src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/testutils.rs, tests/test_chain.py
Previously we would not detect whether the transaction for an unconfirmed deposit was still in our mempool. For instance a deposit that was RBF'd would result in us storing two coins, the replaced and the replacement. Keeping the unconfirmed replaced coin forever.
Fix this by dropping unconfirmed coins from our database if their transaction isn't in our mempool (anymore).
Fixes #72.
=> Handle unconfirmed deposits that were replaced

gui/src/app/state/spend/detail.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs
I wanted the refresh button to add more harware wallet to the list without erasing the previous list
in order to not cut the existing communication channels.
But with the new display of "unsupported wallet" this behaviour can corrupt the list. An "unsupported wallet" can become "supported" because user switch app or unlock.
It is preferable to reset the full list and drop the objects after a refresh.
=> gui: fix hws list reloading

gui/src/app/view/spend/step.rs
"> 5000 sats" message was confusing with the actual amount in btc requirement
=> fix: spend minimal amount in btc

gui/src/installer/step/descriptor.rs
Use needs to be able to start new connections
in the register descriptor step.
=> fix: drop connections to hws in share xpub panel

contrib/release/release.sh
The binary need to be named the same as the configured application name.
=> contrib: fix dmg creation in the release script

src/daemonize.rs
The caller and the definition had them swapped.. So it was logging to the PID file and writing the PID to the log file..
=> daemonize: switch the pid and log file arguments

Cargo.lock, Cargo.toml, src/lib.rs, src/random.rs, src/signer.rs
This introduces a new `signer` module. Its purpose is to provide clients of the Liana daemon (such as the GUI) with tools to sign transactions.
For now, the only signer available is a hot signer based on BIP39. It allows to generate new mnemonics from OS-provided randomness (with added randomness from the CPU if available and mixed-in contextual data). Mnemonics are stored in plaintext in a `mnemonics` folder at the root of a provided data directory.
Fixes #49.
=> Hot wallet support

doc/BUILD.md
I got few errors while building liana-gui with Ubuntu Mate 22.10, then try on a  fresh install with ubuntu 22.04 server (minimal install):
```
running: "cmake" "/home/pythcoiner/.cargo/registry/src/github.com-1ecc6299db9ec823/freetype-sys-0.13.1/freetype2" "-DWITH_BZip2=OFF" "-DWITH_HarfBuzz=OFF" "-DWITH_PNG=OFF" "-DWITH_ZLIB=OFF" "-DCMAKE_INSTALL_PREFIX=/home/pythcoiner/liana/gui/target/release/build/freetype-sys-952a2cbdb10ff868/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
--- stderr
thread 'main' panicked …
```
=> Add dependencies for ubuntu

src/bitcoin/mod.rs
We don't assume that and in fact now use multiple descriptors
=> bitcoin: remove a confusing TODO

gui/src/main.rs
It may removes the annoying logs that occurs after a while.
```
[1669885771][iced_futures::subscription::tracker][WARN] Error sending event to subscription: TrySendError { kind: Full }
[1669885771][iced_futures::subscription::tracker][WARN] Error sending event to subscription: TrySendError { kind: Full }
[1669885771][iced_futures::subscription::tracker][WARN] Error sending event to subscription: TrySendError { kind: Full }
```
By filtering the events to use only the events listened by the application, we may not reach some buffer size limit
=> gui: filter unused events

doc/BUILD.md
They weren't the clearest. Someone was confused they couldn't build the GUI with an old `cargo`. Make it clearer.
=> doc: clearer build documentation

gui/src/app/state/spend/step.rs
This is to resolve #190.
The check for a duplicate is skipped if the recipient address is an empty string.
I was able to run the GUI locally and it seemed to work as required.
=> gui: do not check empty addresses for duplicates

doc/API.md, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/database/sqlite/utils.rs, src/lib.rs, src/testutils.rs, tests/test_framework/utils.py, tests/test_rpc.py
This is an alternative to #390. 
We add a new column in the `spend_transactions` SQLite table, and as such introduce a straightforward migration system. This field is in turn always set in `updatespendtx` when we store the new PSBT, and listed in `listspendtxs` entries. It is useful for instance to sort spend transactions on the GUI (#281).
=> Store in DB the time a Spend transaction draft was last updated

gui/src/daemon/client/mod.rs
Wrong order.
We should find a way to test the jsonrpc client agains the liana rpc api.
=> fix gui jsonrpc client: wrong createspend args

gui/ui/src/component/hw.rs
The error may not be due to an unsupported version. For instance the device may just be locked. In these cases telling the user to update their device is very misleading.
Fixes #418.
=> gui: fix a misleading tooltip on hw connection error

gui/src/app/state/spend/detail.rs, gui/src/app/view/hw.rs, gui/src/app/view/spend/detail.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs, gui/src/signer.rs, gui/ui/src/component/hw.rs
When a hot signer is suggested to user and an alias was entered then the alias must be displayed with the "This computer" label as signer kind.
=> Add alias to hotsigner component

Cargo.lock, Cargo.toml, src/commands/mod.rs, src/descriptors/mod.rs
This is to avoid creating descriptors containing `a:pkh()` fragments for now.
Note how this PR targets the 0.4 branch. For master, we keep the `pkh` compilation.
=> lianad: update rust-miniscript to use a tweaked compiler

gui/src/app/view/settings.rs
The wallet descriptor is cut in wallet settings, while this fix does not improve totally the UX it enable the user to have a total view of the descriptor
=> Add scrollable to descriptor in wallet settings

.gitignore
It simplifies a little bit my life when doing `VERSION=0.4 ./contrib/release/release.sh`
=> Add Xcode_12.2.xip to .gitignore

gui/src/app/state/mod.rs, gui/src/app/view/receive.rs
This aims to resolve #114.
I've added a "Next" button to the Receive screen, which gets a new address. I'm not sure if I've done this the right way and will be happy to make any changes as required.
I compared several addresses against those returned by `bdk-cli` and they matched.
Thank you.
=> gui: add button to get next receive address

src/lib.rs, tests/test_rpc.py
Let's use `u32::MAX` as patch version to denote a development build.
=> Reset the daemon and GUI versions post 0.4 branch-off

gui/src/installer/view.rs
This is to resolve #436.
For the alias, I'm selecting the element from `context.keys` that has the same fingerprint as `hw` / `context.signer` and then displaying the name of this key. This logic could possibly be extracted to a function.
I haven't yet been able to test with a hardware device, but will try to get my Specter DIY up and running soon :)
=> gui: display aliases on installer final step

gui/src/app/view/home.rs
We still list the self-send transactions but
we do not display them, because they are required
in order to have the next timestamp for the pagination. This commit fix a misplaced filter that mixed up
events index for the event selection.
close #463
=> fix: home list events filter

gui/src/installer/context.rs, gui/src/installer/mod.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/step/mnemonic.rs, gui/src/installer/step/mod.rs, gui/src/installer/view.rs
It is a refont of the installer flow
to use less optional components in the installer context.
Hot signer is stored a the install step if its fingerprint is present in the descriptor string
close #397
=> Check hot signer usage using descriptor

gui/src/installer/view.rs
The height of the content was filling too much and user can scroll down to the abyss
=> fix installer final step view

src/bitcoin/d/mod.rs, src/lib.rs
=> lib: on Windows unload the watchonly wallet before deleting it

tests/README.md
@darosior  I tried following the testing instructions and I got an error that indicated that the `target/debug` directory did not exist. This PR adds instructions that specifically ask devs to build the project before testing. I think this will be helpful to others when trying to run the tests.
=> Add instructions to build daemon for testing

src/bitcoin/d/mod.rs
We should really be less picky in the bitcoind interface... Too many unnecessary assertions.
=> bitcoind: do not assert presence of 'warning' field in unloadwallet response

.cirrus.yml, doc/TRY.md
Leave minimum supported version as 24.0.1.
=> doc/ci: Use Bitcoin Core 24.1

Cargo.toml, src/random.rs
I ran into some issues while trying to build this on an M1 Mac. First, the `bip39` crate was somehow not being imported correctly and secondly there wasn't a way to just use the `hardware_randomness()` if `cpu_randomness()` wasn't available. Not sure how to do the `#[cfg]` stuff correctly so feel free to close and do another way. Just wanted to post somewhere in case someone else runs into this.
=> Make compilable on aarch64 (M1)

.cirrus.yml, doc/TRY.md
Leave minimum supported version as 24.0.1.
=> doc/ci: Use Bitcoin Core 25.0

.github/workflows/main.yml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, doc/BUILD.md, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs
The latest Debian stable was released this month with support for Rust up to 1.63.
Fixes #69.
=> Update our MSRV from 1.48 to 1.54

Cargo.lock, Cargo.toml, gui/Cargo.lock, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/commands/utils.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/descriptors/analysis.rs, src/descriptors/keys.rs, src/descriptors/mod.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/lib.rs, src/random.rs, src/signer.rs, src/testutils.rs
It was a big chunk, especially in making sure we don't introduce any silent bug with all the upstream recent code movements.
Also, we no longer depend on my custom `rust-miniscript` branch! :tada:
=> Update `rust-miniscript` (and thereby `rust-bitcoin`) to latest version

doc/API.md
This fixes the documented order of parameters for the `createspend` command.
I also added a full stop to the `destinations` description for consistency.
=> doc(api): fix order of params for `createspend`

Cargo.lock, Cargo.toml, src/bitcoin/d/mod.rs, src/lib.rs, tests/test_misc.py
This makes us take advantage of a more robust, but still lightweight, HTTP implementation.
This PR also cleanups our error handling code and adds a functional test checking we do retry request on transient bitcoind failures.
=> Update `rust-jsonrpc` and switch to using `minreq`

src/descriptors/analysis.rs, src/descriptors/mod.rs
This is unnecessary to bump a hardened step to get another xpub for the same participant:
- It's more hurdle when sharing it
- It's more hurdle when verifying it on the device's screen
- It's for the same person within the same script anyways
Fix this by allowing to use the same xpub multiple times in a descriptor as long as the derivation path is different. Then the GUI will be able to use a new unhardened derivation step instead of bumping the BIP48 "accounts". A unit test is introduced that showcases this.
See also https://github.com/wizardsardine/liana/issues/542.
=> descriptor: make it possible to reuse xpubs at different derivation paths

src/bitcoin/d/mod.rs
Upon startup bitcoind will update loaded wallets before pruning historical chain data.
This is a trivial fix for people using an aggressively pruned `bitcoind` to not be forced to `-reindex` if they haven't started their Liana wallet for longer than their prune target allows for.
See https://github.com/wizardsardine/liana/issues/570#issuecomment-1658108967 for a discussion about this.
=> bitcoind: create watchonly wallet with `load_on_startup = true`

.cirrus.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, gui/Cargo.lock, gui/Cargo.toml, gui/src/hw.rs, src/bitcoin/d/mod.rs, src/lib.rs, tests/test_rpc.py
Some bug fixes for 1.0 to be released before 2.0 is out.
The first commit is from #551 to fix a connection bug to the Specter DIY.
=> 1.1 backports

src/database/sqlite/utils.rs
As suggested by Edouard in https://github.com/wizardsardine/liana/pull/578/files#r1285476881 there is no reason not to keep the `NOT NULL` constraint. I also added the `CHECK .. IN (0, 1)`.
This adds an extraneous DEFAULT compared to the schema in freshly created databases, but anything else (altering the column in an SQLite-friendly way after setting all NULL values to 0) would be way too involved.
=> db: keep NOT NULL constraint on is_immature in migration

src/descriptors/analysis.rs, src/descriptors/mod.rs
Ledger and wallet policies disallow having more than 2 depth after the
placeholder, therefore we can't do `@1/0/<0;1>/*`, `@1/1/<0;1>/*`, ..
Instead we have to do `@1/<0;1>/*`, `@1/<2;3>/*`, ..
Why not? Salvatore also says the cost of deriving another depth is
non-trivial on a signing device.
Don't pick a fight with Salvatore, instead just let the GUI (or whatever
creates the desc) use different multipath steps for keys derived from
the same xpubs.
Based on #584. We need to make sure we don't make the assumptions of the multipath step always being `<0;1>` anywhere else the codebase.
=> Descriptors: allow the multipath step to be different from `<0;1>`

src/bitcoin/d/mod.rs
we used to not set 'load_on_startup' when creating a watchonly wallet. This could create some complications when people are using agressive pruning configurations.
Fix this by overwriting this parameter when loading watchonly wallets. We can always revert this in the future if for some reason a user wants to have it set to false and no be overwritten everytime Liana loads it.
Fixes #594.
=> bitcoind: set `load_on_startup` to `true` when loading watchonly wallet

src/bitcoin/poller/looper.rs, tests/test_chain.py
It turns out we didn't actually notice RBF'd spends.
Fixes #382. And also fixes #73.
=> poller: spend transaction RBF handling

src/bin/daemon.rs
Specifically, link to a sample configuration file. How are users supposed to know how to write the config file otherwise?
Fixes #559.
=> `lianad`: print a more helpful error message on startup failure

gui/Cargo.lock, gui/Cargo.toml, gui/src/app/state/coins.rs, gui/src/app/state/recovery.rs, gui/src/app/view/psbt.rs, gui/src/app/view/recovery.rs, gui/src/daemon/model.rs, gui/src/hw.rs, gui/src/installer/message.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs
EDIT (by Antoine): this also fixes #337.
=> gui installer: append derivation path to xpubs

gui/src/installer/mod.rs, gui/src/installer/prompt.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs
As discussed in #545, in some cases we nudge the user to register the descriptor on their signing device although they might not have one. Those cases only ever arise when importing a descriptor (either when recovering from backup or participating in the creation of a descriptor on another laptop), since when the descriptor is created beforehand we can simply detect whether a signing device was used and thereby needs to be registered (implemented since https://github.com/wizardsardine/liana/pull/470). 
Therefore, detect when the registration step arises as part of an import process and if so adjust the language to convey registration on a signing device may not be necessary.
Result:
Fixes #545.
=> gui: installer: convey registering on a signing device isn't always required

Cargo.toml, src/bitcoin/poller/mod.rs, src/lib.rs
This makes it possible to trigger the shutdown of the daemon through the DaemonHandle, without having to block while waiting for the poller thread to join.
Incidently, this allows to avoid having to move `self` which in turns allows to fix a GUI bug (see
https://github.com/wizardsardine/liana/issues/622).
=> lib: non-blocking daemon shutdown

tests/test_framework/lianad.py
It seems to be causing some races that i don't want to be investigating at the moment. It's redundant anyways as we are already checking for the return code of the process.
It's fixing the annoying "Process died while waiting for logs" when stopping the daemon. AKA:
> Yes it died i stopped it that's the point.
=> tests: don't wait for lianad to log on shutdown

src/bitcoin/d/mod.rs
As we walk through the spend transactions in the wallet, we may return the txid of the transaction that was replaced instead of the new one.
Note: this fixes the `test_conflicting_unconfirmed_spend_txs` flakiness, which exposed this bug.
=> bitcoind: fix the detection of unconfirmed RBF spending txs

README.md, contrib/release/release.sh
Keeping it draft until we actually publish the package.
=> README: mention the Debian package

src/bitcoin/d/mod.rs, src/lib.rs, tests/test_framework/lianad.py
At startup it sometimes appear we may be hanging when setting up bitcoind. Add more logging to give more information about what's taking long to setup (for instance, loading the watchonly wallet).
Related to https://github.com/wizardsardine/liana/issues/475.
=> Add more bitcoind-related setup logging

gui/src/installer/view.rs
=> installer: remove legacy warning on incompatible descriptor.

src/bitcoin/d/mod.rs, src/lib.rs, tests/test_misc.py
See the added comment for the details. No need to store the watchonly wallet under bitcoind's datadir anymore. :tada: :tada:
I've noticed this while working on fixing #630 on Windows which failed for the same root reason as why the watchonly wallet path didn't work on Windows.
Fixes #653.
=> lib: implement a superior workaround for the watchonly wallet on Windows

gui/src/app/mod.rs, gui/src/app/state/settings/bitcoind.rs, gui/src/app/state/settings/mod.rs, gui/src/bitcoind.rs, gui/src/installer/context.rs, gui/src/installer/message.rs, gui/src/installer/mod.rs, gui/src/installer/step/bitcoind.rs, gui/src/installer/view.rs, gui/src/loader.rs, gui/src/main.rs
- Small rearrangements of the bitcoind module.
- Add a wrapper around the bitcoind child process and share it to the states:
Installer -> loader -> app
- It makes it more easy to share the information if the gui started a bitcoind process, no need anymore to check multiple configuration files, just answer the question: do we have a child process started ?
=> cleanup bitcoind process management

gui/src/bitcoind.rs, gui/src/utils/mod.rs
We would formerly wait a definite number of seconds for the cookie file to appear. But this approach presents a fundamental issue: how long is enough before we can be reasonably sure bitcoind will never start?
For instance on mainnet the checks performed at startup could take more than the 3 seconds we would previously wait for. If it does we would have incorrectly errored and let bitcoind run in the background.
Instead, assume bitcoind would exit if it errors. Until it does so, continue polling for the cookie file. This approach also presents drawbacks (for instance what if bitcoind is performing a very long operation before creating the cookie file?), but the former approach wouldn't be an acceptable solution in this case either. And the new one is preferable as its failure scenario …
=> gui: installer: more robust poll for cookie file at bitcoind startup

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs, tests/test_rpc.py
This is assuming #630 is merged, but not the fix for #323 (can be added to the CHANGELOG if it does).
=> Prepare v2 release

gui/src/installer/step/bitcoind.rs
This will ensure we can retry starting internal `bitcoind` in case of transient errors.
=> gui: ensure we can retry starting in case of error

CHANGELOG.md, gui/src/installer/view.rs
This is a quick and dirty fix to be backported. Doing something like #291 could make sense in the future.
=> GUI: installer: don't generate multiple times the same xpub in "participate"

doc/API.md, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/jsonrpc/api.rs, src/testutils.rs, tests/test_rpc.py
This is to resolve #676.
I've renamed `CoinType` to `CoinStatus` and updated its values.
The `listcoins` command and related functions can be optionally filtered by coin status and/or outpoint.
Opening this as draft to check that I'm on the right track.
Remaining tasks:
=> commands: optionally filter `listcoins` by status and outpoint

gui/src/installer/view.rs
This is to resolve #714.
The "Starting..." message will now be shown also in case bitcoind was already installed on a previous occasion:
=> installer: show message when starting already-installed bitcoind

gui/src/loader.rs
This is to resolve #646.
I've added the specified text to the synchronisation screen and also display the progress as a percentage above the progress bar.
This is how it looks (on signet with Liana-managed bitcoind):
Also, for external bitcoind:
=> gui: show more info on synchronisation screen

gui/src/installer/mod.rs, gui/src/installer/step/mod.rs, gui/src/installer/view.rs
This is to resolve #679.
The following changes have been made:
- Change title of final step to "Finalize installation"
- Install and load wallet automatically when reaching final step
- Remove fields from `Final` step that are no longer used
This is how the page looks when installing:
The following is only shown for ~1 sec once wallet has been installed and before loading wallet:
=> installer: Finalize installation and start automatically on final step

gui/src/app/state/recovery.rs, gui/src/app/state/spend/step.rs, gui/src/app/view/home.rs, gui/src/app/view/psbt.rs, gui/src/app/view/transactions.rs, gui/src/daemon/mod.rs, gui/src/daemon/model.rs
This is to resolve #558.
For transactions that have been broadcast, the feerate is calculated using the transaction's actual size. For PSBTs, the feerate is calculated using the max satisfaction size for all inputs, whether they have been signed or not (see https://github.com/wizardsardine/liana/issues/558#issuecomment-1750128022).
In both cases, the calculated feerate currently has type `u64`.
This is an example of a transaction on the Home tab:
The same transaction on the Transactions tab:
On the PSBTs tab, the feerate is an estimate:
=> gui: display (estimated) feerate

src/bitcoin/d/mod.rs
This was necessary to transition wallets that were created without this flag, but since v2 they are always created with it so this is redundant: it'd unnecessarily try to update the flag over and over again on bitcoind's side, always with the same value.
Fixes #641.
=> bitcoind: don't set load_on_startup when loading watchonly wallet

gui/Cargo.lock, gui/src/app/message.rs, gui/src/app/mod.rs, gui/src/app/settings.rs, gui/src/app/state/coins.rs, gui/src/app/state/label.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbt.rs, gui/src/app/state/recovery.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs, gui/src/app/state/transactions.rs, gui/src/app/view/coins.rs, gui/src/app/view/home.rs, gui/src/app/view/label.rs, gui/src/app/view/message.rs, gui/src/app/view/mod.rs, gui/src/app/view/psbt.rs, gui/src/app/view/psbts.rs, gui/src/app/view/receive.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/transactions.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/daemon/model.rs, gui/ui/src/component/badge.rs, gui/ui/src/component/event.rs
This PR use the lianad update_labels and get_labels commands.
It also introduce new concepts from talks with Kevin and Antoine:
- User spending is creating a payment, when he does not add multiple recipients anymore, he is doing multiple payment in one bitcoin transaction.
- a transaction that have multiple outgoing outputs (multiple payment) is tagged as a 'Batch'.
=> Gui labels

src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/commands/mod.rs, src/descriptors/mod.rs, src/lib.rs, src/testutils.rs
Fixes #726. We actually do update our internal state before we are synced but we weren't waiting for the chain to be entirely synced.
=> Make sure we're actuall caught up to tip before starting up

src/descriptors/analysis.rs, src/descriptors/mod.rs, src/signer.rs, tests/fixtures.py, tests/test_misc.py
This is necessary to support signers which sign for a single key at once. It also doesn't make any sense to reuse a signer within the same spending path, so rule it out before it creates any new edge cases.
For more about the Bitbox signer support, which motivated this change, see
https://github.com/wizardsardine/liana/pull/706#issuecomment-1744705808.
=> descriptors: prevent using a signer more than once in a single path

src/commands/mod.rs, src/descriptors/mod.rs
The `sanity_check_psbt()` function checks, among other things, that the feerate in sats/vbytes is in the required range. When estimating the transaction size, converting each part to vbytes first can lead to a larger result due to rounding multiple times and therefore a lower feerate, which could fall below 1 and fail the sanity check.
This issue has arisen in #560 when creating a transaction using coin selection.
=> commands: add weights before converting to vbytes

src/commands/mod.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_rpc.py
When creating a PSBT, we were checking whether the key was for this path by checking its origin. This check would return false positive for keys from other paths but same signer (which shares the same fingerprint).
Instead, check the entire origin for each key to make sure it's actually the one used in the path we are interested about.
Thanks to Edouard Paris for finding this bug.
=> commands: don't add derivation paths for keys from different path but same signer

gui/src/app/view/home.rs, gui/src/app/view/psbt.rs, gui/src/daemon/model.rs
close #738
liana-gui v2 also tried to display addresses from transaction outputs to user when clicking on transaction detail.
=> gui: coinbase transaction output scripts may not represent valid addresses

gui/src/bitcoind.rs, gui/src/installer/step/bitcoind.rs
This PR bumps the managed bitcoind version for new Liana installations to 25.1.
The GUI will look for the most recent managed bitcoind version available when starting bitcoind.
Once a new managed bitcoind version is installed, all wallets using managed bitcoind will use this new version, even if a wallet on a particular network was installed with a previous bitcoind version.
The approach taken here may change as part of #690.
=> gui: Bump managed bitcoind version for new installations to 25.1

doc/API.md, src/commands/mod.rs, src/descriptors/mod.rs, src/jsonrpc/mod.rs, src/signer.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_rpc.py
#722 pruned the BIP32 derivation paths in PSBT inputs for other spending paths than the one this PSBT was created for. This was to make it possible to use them with the Bitbox (see #722 OP for more details).
These were merged without testing at all whether it would break signing with a Ledger Nano. Turns out it did. Our bad. Thanks to Pythcoiner for finding this bug.
A follow-up PR will add a helper to prune the derivation separately so that it can only be applied to some signers and not all of them.
=> Revert PRs #722 and #742: roll back to including all BIP32 derivations in the PSBT input

gui/src/app/wallet.rs
If an wallet settings already exists, the wallet name attached to the hardware wallet credentials must be use, instead of the new generated one.
close #745
=> wallet: load name from settings

doc/API.md, src/commands/mod.rs, src/descriptors/mod.rs, src/jsonrpc/mod.rs, src/signer.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_rpc.py
Based on #749, this provides clients of the library with a way to prune all the BIP32 derivation paths in a PSBT for keys which are not part of the given spending path.
=> descriptors: introduce a helper to prune BIP32 derivation paths

Cargo.toml
We had too many keywords to be able to publish on crates.io
=> Cargo: drop two keywords

gui/src/app/state/psbt.rs, gui/src/app/wallet.rs, gui/src/installer/context.rs
DEFAULT_WALLET_NAME aka simple `Liana` was still used during creation of wallet settings during install
this should have been noticed if I did test the wallet creation process in detail and if I removed the public exposition of the const variable. SHAME
based on #760
=> fix wallet name in settings during install

gui/src/app/view/home.rs, gui/src/app/view/psbt.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/transactions.rs
When a transaction has only one payment,
then its txid label is attached to the payment label. While modifying the label of an output it did not change the whole transaction label, which is a bug.
=> fix single payment output label

gui/src/app/state/psbt.rs
=> fix gui: update labels if user signed an unsaved tx

gui/src/installer/mod.rs
If a user clicked very fast a lot on the Next button to trigger multiple Next messages, then the last
step of the install reloads multiple time.
This commit introduce a check that ignore next message if the step is the last one.
=> installer: do not reload last step on next message

gui/src/installer/step/bitcoind.rs
In case the user clicks on "Previous" before the bitcoind download has finished, this PR will clear the incomplete download (or a download that completed with errors) from `InternalBitcoindStep`.
If the user then returns to this step, either a new download will start or the finished download will be available still. This fixes a bug following #746 for users that already have bitcoind v25.0 installed. If they click "Previous" while downloading 25.1, then upon returning to this step, the existing 25.0 bitcoind will be started.
=> installer: start new bitcoind download if not finished previously

gui/src/installer/step/bitcoind.rs
In case user clicks on Previous before bitcoind download has finished, this will clear the incomplete download from `InternalBitcoindStep` so that a new download will start if the user returns to this step.
=> 3.x: Backport #777:  "installer: start new bitcoind download if not finished"

gui/src/loader.rs
Maybe we should just get rid of the filtering since there is no stability guarantees wrt logging. On the other hand we'd probably need to increase the update frequency if we do that. In the meantime at least display also the blockheaders so the sync doesn't appear to be stuck for 5 minutes at startup.
Fixes #780.
=> gui: display headers sync progress too in loader

doc/API.md, src/commands/mod.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, tests/test_rpc.py
address #681 
todo:
edit: i'm really new to rust, don't hesitate to kick my ass when i write stupid code
=> Implement listadresses

src/database/mod.rs
Comparing the address itself includes the network, but an unchecked signet address will have its network set as testnet by `assume_checked` and so change addresses will not be matched.
=> db: check for change using address strings only

Cargo.lock, Cargo.toml, doc/API.md, src/commands/mod.rs, src/commands/utils.rs, src/jsonrpc/mod.rs, tests/test_rpc.py, tests/test_spend.py
These are some initial changes towards #51.
I've added a `selectcoinsforspend` command that applies BnB coin selection using a waste metric.
This coin selection is then used in `createspend` if no coins are specified.
@darosior The changes are still in their early stages so I'm creating this draft PR to facilitate discussion about the approach in general and specific details.
=> Apply coin selection for spend

doc/API.md
The derivation index is required for
for client to derive and verify the address
on hardware wallets.
=> Add derivation_index to GetAddressResult

gui/Cargo.lock, gui/src/app/error.rs, gui/src/app/state/spend/step.rs, gui/src/app/view/warning.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs
This adds automated coin selection from #560 to the GUI.
The new "Auto-select" button uses automated coin selection to select coins for a spend, which the user can then modify as required.
The button can only be clicked once the recipients and feerate have been validated, and it does not appear when creating a self-send.
I haven't added any validation on the amount before making the button clickable, but it may be hard to anticipate all coin selection errors once fees are taken into consideration.
=> gui: Add automated coin selection for spend

src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/testutils.rs, tests/test_chain.py
We start by illustrating the current logic of the poller with regard to replacements in a functional test. This exposes a bug: we could incorrectly assign a transaction which conflicts with a spend transaction for one of our coin as spending this coin whereas it in fact didn't.
After fixing this bug, we proceed to make it possible to wipe the spending status back to unspent. First when a conflict is mined, then also when it's only accepted into our mempool. This matches how we treat replacements for deposit transactions.
=> Bitcoin state poller: a bug fix and a few RBF handling improvements

tests/test_chain.py
Since #617 the spend info for a coin may be wiped from the DB. Be robust to a temporarily `None` spend info in the functional test.
See for instance https://github.com/wizardsardine/liana/runs/18785511349.
=> qa: fix flaky test of unconfirmed spend RBF

src/commands/mod.rs, src/commands/utils.rs, tests/test_spend.py
This adds a new `LowestFeeChangeCondition` metric for use in coin selection. It's the same as `LowestFee` with the option to only find solutions with change.
This option is then used for self-sends to ensure only a solution with change will be returned.
=> commands: require change for self-send

doc/API.md, src/commands/mod.rs, src/jsonrpc/api.rs, tests/test_spend.py
We add a way to specify what change address to use. This allows the caller to set an external address which has for effect to sweep all the inputs' value to this address, after deduction of the fees and the other (optionally) set destination addresses.
For instance, combined with a self-send (no other destination) and by setting all the wallet's unspent coins, this allows one to sweep all the funds of the wallet to an external address.
=> Make it possible to create a sweep transaction using `createspend`

doc/API.md, gui/src/daemon/model.rs, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/commands/mod.rs, src/commands/utils.rs, src/jsonrpc/api.rs, src/jsonrpc/mod.rs, src/testutils.rs, tests/test_chain.py, tests/test_framework/utils.py, tests/test_misc.py, tests/test_rpc.py, tests/test_spend.py
This PR relates to #43 and #236.
It adds a `rbfpsbt` command that generates a PSBT to replace an existing transaction using RBF. This replacement can either preserve non-change outputs and simply bump fees or remove non-change outputs and effectively cancel the transaction. The inputs and change output may need to be updated in accordance with the higher fee.
I've also added a `getmempoolentry` call to the bitcoin interface that is used for checking information about descendant transactions.
To facilitate development, I've made some temporary changes in the GUI so that replacement PSBTs can be signed and broadcast, but these changes might not be part of this PR in the end.
=> commands: add `rbfpsbt` command

Cargo.lock, Cargo.toml
Draft until https://github.com/bitcoindevkit/coin-select/pull/9 is published on crates.io.
=> Cargo: use the published bdk_coin_select

gui/src/bitcoind.rs
=> gui: upgrade managed bitcoind version to 26.0

gui/src/app/view/hw.rs, gui/src/hw.rs, gui/ui/src/component/hw.rs
=> Grey out harware wallets when unrelated or do not support method

gui/Cargo.lock, gui/src/app/menu.rs, gui/src/app/mod.rs, gui/src/app/state/psbts.rs, gui/src/app/state/transactions.rs, gui/src/app/view/message.rs, gui/src/app/view/transactions.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/loader.rs
This is to resolve #43.
When viewing an unconfirmed transaction, a user can now either bump its fee or cancel it. This will generate a new PSBT that the user can jump to in order to sign and broadcast it.
I haven't added any comparison between the previous and replacement inputs as suggested in https://github.com/wizardsardine/liana/issues/43#issuecomment-1825623520. I think that would be a bigger change and might be better as a follow-up.
I decided not to add "Unconfirmed" on the transaction screen as suggested in https://github.com/wizardsardine/liana/issues/43#issuecomment-1831763013 as I thought it might be better as a separate PR.
I haven't yet added the RBF buttons to the home screen, but that could also be done as a follow-up :)
In a separate commit, I pass `None` to `create_spend` …
=> gui: enable use of RBF on unconfirmed transactions

src/spend.rs
Based on #842.
Performing BnB with a large number of candidates can be computation expensive. Especially in debug mode. It can make the software lag in situations where it's called repeatedly.
Reasonably scale down the number of rounds performed depending on the number of candidates and whether optimizations are enabled.
Fixes #846
=> spend: Scale down the number of BnB rounds in debug mode and with a high number of candidates

doc/API.md, src/commands/mod.rs, src/lib.rs, tests/test_rpc.py
In order to externally use create_spend, the spend module must be exposed and the listcoinsentry must include the derivation_index and is_change fields.
=> Expose spend module and coins fields

gui/Cargo.lock, gui/src/app/error.rs, gui/src/app/state/coins.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/warning.rs, gui/src/daemon/embedded.rs
=> Use create_spend to calculate amount left to select and coin selection

gui/src/app/state/transactions.rs, gui/src/app/view/transactions.rs
This applies a similar change to feerate form validation as in #863 to ensure value is not too high.
=> gui: set max feerate in RBF modal

src/spend.rs, tests/test_spend.py
This is a temporary partial fix for https://github.com/bitcoindevkit/coin-select/issues/6 that should be reverted once the upstream fix has been made.
When calculating the score, the excess should be added to changeless solutions instead of those with change.
Given a solution has been found, this fix adds or removes the excess to its incorrectly calculated score as required so that two changeless solutions can be differentiated if one has higher excess (and therefore pays a higher fee).
Note that the `bound` function is also affected by this bug, which could mean some branches are not considered when running BnB, but at least this fix will mean the score for those solutions that are found is correct.
The new functional test included here fails without this fix.
=> spend: a temporary partial fix for `LowestFee`

gui/src/hw.rs
During the install process, no wallet yet is created and bitbox should not be marked as unsupported if
its fingerprint is not in any descriptor.
=> fix bitbox unsupported status when no wallet yet

gui/src/hw.rs
During the install process, no wallet yet is created and bitbox should not be marked as unsupported if
its fingerprint is not in any descriptor.
=> Backport #879 : fix bitbox unsupported status when no wallet yet

gui/Cargo.lock, gui/src/daemon/model.rs
This is to resolve #880 using the new helper function from #881 to get the max possible size of the unsigned transaction.
The following screenshot is taken using both new and old implementations together and shows the new estimated feerate changes from 0 to 1 sat/vbyte:
=> gui: use descriptor helper function to get unsigned tx max size

src/lib.rs, tests/test_misc.py
It was introduced as a temporary hack in v2 (released in August 2023) for migrating datadirs created on Windows using Liana v1 (May 2023).
Presumably Windows users wouldn't have used the beta versions which preceded v1 release with any real funds. This removal would go in v5, released around end of January / early February. Presumably any Windows user who created a mainnet datadir within the 3 months period where the bug was present would have opened its Liana at least once in the following 6 months after the migration was released.
In the unlikely case a user on Windows created a mainnet wallet on the very first release of Liana, funded it, didn't touch it for more than 6 months and tried to open it later using the latest version of Liana available they are instructed to first run Liana …
=> Drop watchonly wallet migration for old Windows datadir

contrib/lianad_config_example.toml, src/bitcoin/d/mod.rs, src/config.rs, src/lib.rs
As a first step towards #356, this adds the option to specify a user and password in Liana's config file for bitcoind RPC authentication.
The GUI installer & settings will need to be updated in a follow-up PR to add this option.
=> config: add user:password option for RPC authentication

gui/src/app/mod.rs
This is required in case the updated config file has a shorter length than the existing file.
For example, if changing cookie path from absolute path to relative path, the updated config file will have invalid content without this change.
=> gui: truncate config file before writing

gui/src/app/state/settings/bitcoind.rs
Currently, the Bitcoin Core settings page doesn't show the updated values after saving changes and needs to be reloaded in order to refresh. This change makes the Bitcoin Core settings page reload after changes are saved so that they are shown immediately.
=> gui(settings): load updated bitcoind settings after saving

gui/Cargo.lock, gui/src/app/state/settings/bitcoind.rs, gui/src/app/view/message.rs, gui/src/app/view/settings.rs, gui/src/bitcoind.rs, gui/src/installer/message.rs, gui/src/installer/step/bitcoind.rs, gui/src/installer/view.rs, gui/ui/src/theme.rs
This adds support to the GUI for user and password RPC authentication as part of #356.
The first commit adds the user/password option to the settings page, and only updates the installer as required for it to compile. It also changes how the managed bitcoind gets the cookie location when starting so that it doesn't rely on the config file.
The second commit adds the user/password option to the installer when using a self-managed node.
Updating the managed node to use user/password can be done in a follow-up PR.
=> gui: support user/password for RPC authentication

.github/workflows/main.yml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/descriptors/analysis.rs, src/descriptors/mod.rs, src/jsonrpc/api.rs, src/signer.rs, src/spend.rs, src/testutils.rs
New years' cleanup!
Our MSRV was becoming too restrictive to keep being able to benefit from the latest releases of our dependencies. Strike a better balance between not requiring a recklessly new compiler and still being able to get upstream bug fixes.
From this update most of our dependencies to their latest point releases. Then upgrade rusqlite, jsonrpc and rust-[bitcoin, miniscript] to their latest major version. Note their is a ton of updates. I've done a minimal due diligence to check what was updated, to what version, what changed, but i can't realistically audit all the code changes this is effectively pulling. I think we need to look into `cargo-crev`.
Take the opportunity to apply some clippy cleanups, and bump the version we're using in CI.
See commit messages for details.
=> Bump MSRV, upgrade dependencies and clippification

gui/src/installer/view.rs
Simple text change to add bitcoind version number to download wording as per #858. First issue exploration.
=> #858: Change text when downloading Bitcoin to include version number

doc/API.md, src/commands/mod.rs, src/spend.rs, tests/test_spend.py
This is a first step towards #811. The GUI will be updated in a follow-up PR.
It adds a warning if there is any change/excess available that has been added to the fee, building on the assumption from https://github.com/bitcoindevkit/coin-select/pull/14 that the decision whether to include change depends on whether the excess is over a threshold. The function `select_coins_for_spend()` now returns this threshold so that the caller can check if the possible change amount is above it.
I've used an `enum` for the different warnings, but could use strings directly.
If the approach looks fine, I'll add some tests.
=> spend: warn when overpaying fee

gui/src/daemon/client/mod.rs
The `is_cancel` parameter gives an "invalid parameter" error when converted to string.
The `feerate_vb` parameter should only be passed if it has a value as otherwise it gives an "invalid parameter" error.
=> gui(daemon): fix `rbfpsbt` params for external daemon

gui/src/app/message.rs, gui/src/app/state/psbt.rs, gui/src/app/state/spend/step.rs, gui/src/app/view/hw.rs, gui/src/app/view/psbt.rs, gui/ui/src/component/mod.rs, gui/ui/src/component/notification.rs, gui/ui/src/component/toast.rs, gui/ui/src/theme.rs
Fixes https://github.com/wizardsardine/liana/issues/644.
=> Gui show transaction detail while signing

gui/src/main.rs
address #263, now if there is a .liana dir already existing but not network folder (`bitcoin`/`testnet`/`signet`/`regtest`) inside, liana start directly into installer (before is was starting the launcher even if no network to launch, and displaying a weird 'Install liana on another network')
=> Go directly to installer if datadir empty

doc/API.md, src/commands/mod.rs, tests/test_rpc.py, tests/test_spend.py
This PR follows a discussion around https://github.com/wizardsardine/liana/pull/873#issuecomment-1886715468.
The GUI uses the `InsufficientFunds` error to get the missing amount when the user is creating a new spend, but it is not straightforward to extract this information in a general way from the RPC error (see https://github.com/wizardsardine/liana/issues/822#issuecomment-1836482355) and instead the spend module's `create_spend` is currently used (see https://github.com/wizardsardine/liana/pull/863).
With this PR, the missing amount will be included in the `createspend` response rather than as an error.
These changes are based on suggestions from @darosior and @edouardparis.
In a follow-up PR, the GUI should revert to using the `createspend` command to calculate the amount left to …
=> commands: include missing amount in spend response

gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs
=> Fix error message when importing desc for wrong network

gui/Cargo.lock, gui/src/app/state/recovery.rs, gui/src/app/state/spend/step.rs, gui/src/app/state/transactions.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/mod.rs, gui/src/daemon/model.rs
This commit also fix handling of create_spend result while updating liana:master
close #841
=> gui: use descriptor method to detect psbt change outputs

gui/src/app/state/spend/step.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs
This PR is a follow-up to https://github.com/wizardsardine/liana/pull/927 and uses changes made in https://github.com/wizardsardine/liana/pull/938.
It reverts to using the `createspend` command in the GUI for automated coin selection and to determine the amount left to select when creating a new spend (which was previously changed in https://github.com/wizardsardine/liana/pull/863).
With this PR, the changes from https://github.com/wizardsardine/liana/pull/873 will become effective in the GUI so that (some) unconfirmed coins are used as candidates and any additional fee to pay for ancestors is included when calculating the amount left to select.
=> gui: use `createspend` command for coin selection and missing amount

gui/src/app/state/settings/bitcoind.rs, gui/src/app/state/settings/mod.rs, gui/src/app/view/message.rs, gui/src/app/view/settings.rs
close #900
After discussion with @kloaec it is better to not return error if date is prior to genesis block date, just take genesis block timestamp
=> gui: display error for rescan past pruned height

gui/src/app/message.rs, gui/src/app/state/psbt.rs, gui/src/app/state/transactions.rs, gui/src/app/view/psbt.rs, gui/src/app/view/transactions.rs
This is for #903.
It adds two warnings to the GUI:
- when creating a new RBF if there are any descendant transactions of the transaction to be replaced:
- when broadcasting a transaction if there are any conflicting transactions
These warnings are generated in the GUI using coins data from the DB and so will not appear if the DB coins have not yet been updated. Would resolving https://github.com/wizardsardine/liana/issues/887 help ensure the coins are updated before running these checks?
=> gui: add warnings for descendant & conflicting transactions that will be dropped

gui/src/installer/step/descriptor.rs
Currently, once the box has been ticked to confirm the descriptor has been backed up, it remains ticked even if the user goes back and changes the descriptor.
This PR will clear the checkbox if the descriptor is changed so that the user knows it needs to be backed up
=> gui(installer): clear checkbox if descriptor is changed

gui/Cargo.lock
This includes the changes from https://github.com/dalek-cryptography/curve25519-dalek/pull/619 and https://github.com/dalek-cryptography/curve25519-dalek/pull/621.
=> gui: bump dependencies to fix nightly build

gui/src/app/state/spend/step.rs, gui/src/app/view/spend/mod.rs
Currently, if duplicate addresses are entered when creating a new spend, the user can click Next and only the second amount will be used for the draft PSBT.
This change prevents the user clicking Next if there are duplicate addresses and stops the `redraft` function running.
=> gui: prevent spend with duplicate addresses

.cirrus.yml, tests/test_framework/utils.py, tests/test_misc.py
I thought there was some hacks i do in the functional tests i needed to update but apparently i was mistaken.
=> ci: bump bitcoind version in functional tests to 26.0

gui/src/app/message.rs, gui/src/app/state/spend/step.rs, gui/src/app/view/spend/mod.rs
This is to complete #811.
It displays any warnings generated by `createspend` on the draft PSBT view, which could currently be those from https://github.com/wizardsardine/liana/pull/905 and https://github.com/wizardsardine/liana/pull/873. Once the PSBT has been saved, these warnings will no longer be shown.
Below are some screenshots.
With a warning:
Without a warning:
=> gui(spend): display warnings for draft PSBTs

gui/src/app/state/spend/step.rs, gui/src/app/view/message.rs, gui/src/app/view/spend/mod.rs
This adds the MAX button from #546.
The max amount is calculated within the `redraft` function based on the change output. The recipient's amount is updated directly within this same function in order to avoid another call to `redraft` after updating the amount.
The MAX button only takes effect once when the user clicks it. If further changes are made (e.g. to feerate or other recipients), the value will not update and the user will need to click MAX again.
Currently, the MAX button is always clickable. It would be possible to determine for each recipient whether the MAX button should be clickable for that recipient (feerate is valid and all other recipients are valid and no duplicates), but it's not a trivial change so I'm not sure if it's worth doing as I think the behaviour is quite …
=> gui: add max button for spend recipients

gui/src/app/menu.rs, gui/src/app/mod.rs, gui/src/app/state/transactions.rs, gui/src/app/view/home.rs, gui/src/daemon/mod.rs
based on #959 
This PR removes the payment section about the transaction inputs outputs for a redirection to the payment transaction (The `See transaction details` button). It makes it easy to fee bump a payment by clicking on it to be redirected to the transaction to rbf
Maybe the UX/UI of the payment should be changed to remove more transaction information, but I fear it makes the panel a little bit empty.
=> gui: add transaction redirection

doc/API.md, src/bitcoin/d/mod.rs, src/bitcoin/mod.rs, src/commands/mod.rs, src/spend.rs, src/testutils.rs, tests/test_spend.py
This is a first PR towards resolving #826 that adds unconfirmed change as coin selection candidates when creating a spend.
As per https://github.com/wizardsardine/liana/issues/826#issuecomment-1853058734, I haven't made any changes to the `rbfpsbt` command.
We will also need to apply the same change in the GUI when selecting candidates for coin selection there (see https://github.com/wizardsardine/liana/pull/863#discussion_r1422823362).
=> commands: include unconfirmed change as coin selection candidates

src/bitcoin/mod.rs, src/commands/mod.rs, src/testutils.rs, tests/test_rpc.py
=> Get genesis timestamp from bitcoind

src/database/mod.rs
This is a preliminary PR towards https://github.com/wizardsardine/liana/issues/677 and is the counterpart to the existing `CoinStatus::from_arg()` method.
This is needed so that the GUI can pass the required string arguments to the `listcoins` RPC command when using an external Liana daemon.
=> database: convert `CoinStatus` to `listcoins` argument string

src/commands/mod.rs, src/testutils.rs, tests/test_spend.py
This is a fix to ensure the change index in the database is incremented if a new spend is created with a change address derived from the current index, regardless of whether this new spend is broadcast or not.
EDIT: The same fix has been applied to the receive index.
=> commands: increment address index if current value used for new spend

src/lib.rs
This is motivated by #929. The GUI will need to generate a salt and password for RPC user/password authentication to the managed bitcoind, and can use this module to get random bytes.
=> lib: expose random module

gui/Cargo.lock, gui/Cargo.toml, gui/src/bitcoind.rs, gui/src/daemon/embedded.rs, gui/src/installer/context.rs, gui/src/installer/step/bitcoind.rs, gui/src/installer/step/mod.rs
This is to resolve #929.
The installer will generate an `rpcauth=` string for use in the managed bitcoind's bitcoin.conf file and will use the corresponding user and password in the Liana daemon config file.
~~The existence of the cookie file is still checked by `Bitcoind::start()` to determine if the process started successfully. An alternative approach could be considered in a follow-up PR (or as part of this one).~~
For https://github.com/wizardsardine/liana/issues/924, we might still need to use the cookie path to stop an already-running process, as we would probably no longer have the password used to generate the previous `rpcauth=` string.
Once https://github.com/wizardsardine/liana/pull/987 is merged, I'll update the Cargo files in this PR.
In the first commit, I move some code …
=> installer: use `-rpcauth` for managed bitcoind

src/bitcoin/poller/looper.rs, tests/test_chain.py, tests/test_framework/utils.py
This change ensures that the spend txid of a coin is updated directly to another value in case a conflicting spend is detected.
The previous order caused the spend txid to first be cleared, which would misleadingly make the coin appear as confirmed
rather than spending.
I've added a new utils function for the functional tests that is a slight generalisation of `wait_for` with an additional condition that must always be met while waiting.
`wait_for` now calls this new function with the condition being one that is always true.
=> poller: unspend expired before new spend

gui/src/app/view/psbts.rs, gui/ui/src/component/badge.rs
this PR try to fix #509
i refactored some badges , moving (optional) `batch` badge before mandatory ones and give fixed positions/size for mandatory badges
before:
after:
=> [GUI] fixed size/position for PSBT badges

gui/src/app/error.rs
Signing fails if another process has an open connection with a Ledger for example. Async-hwi needs to have a more detailed error api in order to handle graciously errors, but for now we provide a hint to what to check for the user
close #381
=> Add default hint for hardware wallet errors

gui/src/installer/view.rs
This is to resolve #866.
I've added the message to the first step where the user enters the descriptor:
=> gui: hint at rescan when importing wallet

gui/src/app/state/receive.rs, gui/src/app/view/message.rs, gui/src/app/view/receive.rs
fix #949:
- Remove Qr code from view
- Add a button `Show QR Code` that display the QRCode in a new modal
- Increased size of Qr Code as we now have more room
=> [GUI] Move qr code to modal

gui/src/app/state/recovery.rs
Once a psbt was generated with the recovery panel
it is impossible for user to start again a recovery process He is redirected to the previous generated psbt because of the panel state being not reset.
This commit reset the panel state on reload.
=> fix recovery panel reload

gui/src/app/state/mod.rs, gui/src/app/state/transactions.rs
when a pending tx is confirmed, it is pushed in the HistoryTransaction list at the end. It should be first in the list. We sort now the list in order to make sure it will be always the case.
=> gui: sort events and txs after push in the list

gui/src/app/mod.rs, gui/src/app/state/coins.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbts.rs, gui/src/app/state/receive.rs, gui/src/app/state/recovery.rs, gui/src/app/state/settings/mod.rs, gui/src/app/state/settings/wallet.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/transactions.rs, gui/src/utils/sandbox.rs
This is to fix https://github.com/wizardsardine/liana/issues/1017.
It adds the `wallet` to the `reload` trait method so that changes are recorded.
As part of this change, the `TransactionsPanel` now has a `wallet` field to be used when calling its own `reload` method.
=> gui: record updates to aliases

gui/src/app/view/spend/mod.rs, gui/ui/src/component/form.rs
This PR replace #977 and fixes #798 
I've followed jp1ac4 advice and create a `Form::new_amount_btc()` method that act like `Form::new_trimmed()` ~w/ few more (filtering) features:~
~- allow only input of "0123456789,." characters~
~- "," is replaced by "."~
~- only one "." separator~
~- maximum 8 digit after separator~
~these features works for keyboard input or paste~
~i've tryied to add a "0" in case the String start with a "." but this make the cursor have a bad location and i do not find a way to control the cursor location w/ iced, so i revert this feature~
=> [GUI] Limit amount to 8 decimal digits

gui/Cargo.lock, gui/Cargo.toml, gui/src/app/state/psbt.rs, gui/src/app/view/hw.rs, gui/src/hw.rs, gui/src/installer/message.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs, gui/src/signer.rs, gui/ui/src/color.rs, gui/ui/src/component/hw.rs, gui/ui/src/theme.rs
=> Gui taproot

gui/src/app/state/transactions.rs
As a follow-up to #959, this clears the RBF modal if the selected transaction changes. e.g. after going to the replacement transaction from the RBF modal and then returning to the Transactions panel and selecting a different transaction.
=> gui: clear RBF modal if selected transaction changes

src/bin/daemon.rs, src/bitcoin/poller/looper.rs, src/bitcoin/poller/mod.rs, src/commands/mod.rs, src/jsonrpc/server.rs, src/lib.rs, src/testutils.rs
Fixes https://github.com/wizardsardine/liana/issues/887.
This takes a couple commits from #909 but takes the approach from there in another direction: we don't externalize the poller, since only a single instance must be ran. Instead we properly keep track of the (up to) two threads we manage in the `DaemonHandle` and provide a way for a user of the library to check for errors in any of the threads.
This approach allows us to 1) communicate with the poller thread from inside the Liana library/daemon (here we leverage this to tell it to poll) 2) eventually (#909) expose all internal errors from the library to the user instead of panic'ing internally.
See the commit messages for details.
=> Update our state upon broadcasting a transaction

gui/src/app/state/spend/step.rs, gui/src/app/view/spend/mod.rs
This issue was encountered by @pythcoiner in https://github.com/wizardsardine/liana_manual_testing/blob/master/tests/v5/v5-pre-rc1/pyth.md#comments.
The `balance_available` value was not being refreshed when new coins were received and so it was sometimes not possible to click Next.
It's enough, however, to check the amount left to select is 0, and so both the `balance_available` and `total_amount` fields can be removed.
=> gui: fix condition to create draft spend

gui/src/app/state/receive.rs
We reintroduce previous behavior:
Reset the list when user leave and come back to the receive panel.
close #1026
=> fix receive panel: reset addresses on reload

src/commands/mod.rs, src/spend.rs, tests/test_framework/signer.py, tests/test_framework/utils.py, tests/test_misc.py, tests/test_spend.py
As discussed with @kloaec, this PR rewords the warning messages when creating a spend.
I didn't include the selected feerate value in the updated messages as that would have required more code changes, albeit fairly simple ones, beyond the message wording itself. I can add those here if required or otherwise in a follow-up.
Here's a screenshot showing the new warnings:
=> spend: reword warning messages

gui/src/app/view/spend/mod.rs
This resolves an issue found by @kloaec. I've changed the tooltip position to `Bottom` instead of `Left` and added some blank spaces so that text is padded at screen edge.
Full screen:
=> gui: make max tooltip more legible

doc/USAGE.md
No need to update this document for every single version anymore. Also, Github doesn't let us access how many people download the binaries.
=> doc/USAGE: point to our website for download

gui/src/app/view/psbt.rs, gui/src/app/view/psbts.rs, gui/src/app/view/recovery.rs, gui/src/app/view/settings.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/transactions.rs, gui/src/installer/view.rs, gui/ui/src/component/text.rs, gui/ui/src/icon.rs
this is preparatory work for #597
=> Use text size constant

Cargo.lock, Cargo.toml, src/commands/mod.rs, src/spend.rs
This is to resolve #923.
The `score` method of the `LowestFee` metric has been fixed upstream and so our temporary partial fix from #867 is no longer required.
The `min_fee` parameter of `select_coins_for_spend`, if positive, now ensures that RBF rule 4 is satisfied. Accordingly, it has been renamed to `replaced_fee` and made an `Option`. We could potentially have used the `SpendTxFees` enum as a parameter directly instead of `feerate_vb` and `replaced_fee`, but `feerate_vb` is currently `f32` rather than `u64` and so I kept them as separate parameters.
Thanks to how the `replaced_fee` parameter works, the fee iteration approach used in `rbf_psbt` to ensure the replacement satisfies [RBF rule 4](https://github.com/bitcoin/bitcoin/blob/master/doc/policy/mempool-replacements.md#current-repla …
=> Bump bdk_coin_select to 0.3.0

gui/src/installer/mod.rs, gui/src/installer/view.rs
This fixes #791 which is regarding the "Participate in new wallet" steps.
The previous step requires the descriptor and so no need to back it up.
I also fixed an issue where it was possible to click Next with an invalid network selected.
=> gui: remove descriptor backup in installer when participating in new wallet

gui/src/app/mod.rs, gui/src/app/state/coins.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbt.rs, gui/src/app/state/recovery.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/transactions.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/loader.rs
This is to resolve https://github.com/wizardsardine/liana/issues/677.
As well as adding the filters to the daemon interface, I've applied filters in separate commits to different sections of the GUI.
This PR builds on changes from https://github.com/wizardsardine/liana/pull/958 and https://github.com/wizardsardine/liana/pull/965. The latter is required when filtering for pending transactions so that a coin whose spending txid changes (e.g. due to RBF) remains as spending.
=> gui: add `listcoins` filters

gui/Cargo.lock, gui/Cargo.toml, gui/src/app/mod.rs, gui/src/app/state/coins.rs, gui/src/app/state/label.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbt.rs, gui/src/app/state/psbts.rs, gui/src/app/state/receive.rs, gui/src/app/state/recovery.rs, gui/src/app/state/settings/bitcoind.rs, gui/src/app/state/settings/mod.rs, gui/src/app/state/settings/wallet.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs, gui/src/app/state/transactions.rs, gui/src/daemon/client/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/loader.rs
This a preparatory work in order to have a lianalite backend connection to satisfy the Daemon trait.
This PR also allows us to use tokio::sync::Mutex for the embedded daemon which goes great with the iced tokio runtime.
=> GUI: change daemon trait to handle async methods

.github/workflows/main.yml, gui/src/app/view/home.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/transactions.rs, gui/src/installer/view.rs
bump rust toolchain to 1.76.0 for gui + fix new clippy warnings introduced by 1.76.0
=> bump clippy rust toolchain to 1.76.0 for gui + fix new clippy warnings 

gui/shell.nix
Nixos 23.11 comes with libc 2.38, this version of libc may not be compatible with some drivers. For now the hack found is to use a community wrapper that detects the requirements and do the link (https://github.com/guibou/nixGL). usage:
nixGL cargo run
=> Add nixGL to gui/shell.nix

contrib/reproducible/guix/guix-build.sh, contrib/reproducible/guix/manifest.scm, contrib/reproducible/guix/patches/rust-1.70-fix-rustix-build.patch, doc/BUILD.md
This is prep work for #597, which bumps the MSRV of the GUI to 1.70.
We are being pulled over in two different directions when it comes to our reproducible builds. On the one hand we need to target reasonably old glibc versions in order to be compatible with older systems. On the other hand the immaturity of the Rust ecosystem makes us require bleeding edge versions of the compiler. With Guix to get the newer versions of the compiler we need to also bump the glibc version.
This was not a sustainable situation. I was planning for a long time to cleanup our reproducible builds. To create a proper Guix package for both the daemon and the GUI using the build system they provide. I had envisioned this way i could rewrite the inputs of the Guix package to use an older glibc, while being able to …
=> guix: use Rust 1.70 for release builds

Cargo.lock, gui/Cargo.lock, gui/src/bitcoind.rs
- bump ahash dependency to fix macos build
- ci requires now macos aarch64 for the liana-gui tests on macos, sha256sum is added for bitcoind-26.1-arm64-apple-darwin.tar.gz (https://bitcoincore.org/bin/bitcoin-core-26.1/)
=> fix ci: bump ahash dep and add bitcoind macos arm64 binary hash

gui/Cargo.toml, gui/src/app/view/label.rs, gui/src/app/view/psbt.rs, gui/ui/src/component/text.rs
Set text shaping and font fallback to text widget.
It enable Emojis
based on #597
=> Gui: enable advanced text shaping :art: 

gui/src/app/config.rs, gui/src/app/mod.rs, gui/src/app/wallet.rs, gui/src/loader.rs
Ledger hmacs, wallet name and fingerprint labels where moved one year ago in the settings.json file.
Here the commit of the new settings module:
https://github.com/wizardsardine/liana/commit/bf1e9e4b808a7c275766975467e637b883524236
A second commit in v4 checked that settings.json is present otherwise it does the migration from the gui configuration file to the settings file:
https://github.com/wizardsardine/liana/commit/3eeba082483c06318ca7a1f018ce2c5da47f5f32
We remove the legacy field from the config field so the wallet module does not depend on the config module anymore to load hardware wallet information.
Tested on gui.toml config with legacy field hardware_wallets and it does not fail to launch.
=> Remove legacy harware_wallets field from gui config

gui/Cargo.lock, gui/Cargo.toml
Include coldcard 0.12.2 that fixes the
nightly build on MacOS
=> bum async-hwi 0.0.18

gui/src/installer/view.rs, gui/ui/src/component/collapse.rs
this PR fixes #1039, it add a warning in the installer if an wallet already exists on mainnet & grey-out `Next` button if the network  is not valid.
=> Add a warning in installer if mainnet wallet already exists

gui/src/app/state/transactions.rs
This fixes #860.
It makes it possible to edit a single-digit feerate, for example, by deleting the existing value and then entering a new one.
=> gui: fix rbf feerate input form

gui/src/app/mod.rs, gui/src/installer/message.rs, gui/src/installer/mod.rs, gui/src/installer/step/descriptor.rs, gui/src/installer/view.rs, gui/src/launcher.rs, gui/src/main.rs, gui/ui/src/color.rs, gui/ui/src/component/mod.rs, gui/ui/src/theme.rs
This Pull requests introduce three changes:
1. Network can only be chosen with the launcher panel. A drop down showing what network user can install is shown to the user when clicking on install a new network.
2. A previous button is added to the first installer page, so user can be redirected to launcher and the network choices if he has chosen the wrong network. close #306 
3. In order to make it clear for the user which network he is actually using or he is currently installing a blue banner is added on top of the window if the network is different than the bitcoin mainnet.
=> Set network in launcher

gui/Cargo.lock, gui/Cargo.toml, gui/src/hw.rs
This pr enable specter support for tap-miniscript.
tested:
- descriptor registration
- spend trough internal key path
- spent trough taptree path
=> Add specter support for tap-miniscript

gui/Cargo.lock, gui/Cargo.toml, gui/src/hw.rs
This reverts commit 876d83af6518a3e4ae45e156ef2952a7e67affc1.
TAP_KEY_SIG was in fact not implemented by specter version 1.9.0 https://github.com/diybitcoinhardware/f469-disco/commit/db3ce3e918cf0fd36f076ecd86ef05240d7c3cef
=> Revert "add specter support for tap-miniscript"

gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbt.rs, gui/src/app/state/psbts.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs
Before changing panel, the previous state may need to release a hardware connection for example.
In order to achieve this we introduce an interrupt method that is used to drop action state.
close #1162
=> Add interrupt method to state trait

gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/state/psbt.rs, gui/src/app/state/psbts.rs, gui/src/app/state/spend/mod.rs, gui/src/app/state/spend/step.rs
Before changing panel, the previous state
may need to release a harware connection
for example.
In order to achieve this we introduce an interrupt method that is used to drop action state.
backport of #1165
=> v6: Add interrupt method to state trait

gui/src/daemon/model.rs
This is to fix #1168.
When estimating transaction size, check if any inputs are using a relative locktime.
I think this logic could later be moved to the `unsigned_tx_max_vbytes` method itself.
=> gui: fix displayed feerate estimate

gui/src/daemon/model.rs
=> [backport] gui: fix displayed feerate estimate

gui/Cargo.lock
To get the fixes since rc1 and drop the rc1 suffix in the version.
=> gui: update Liana to latest

gui/src/installer/view.rs
This PR diasable the previous button  at the descriptor registration step if a device is still processing, avoiding issues like #1158.
The other way around can be to reset the state of `self.processing` if user go back, but look less clean to me.
closes #1158
=> disable previous button if device processing

gui/src/app/state/settings/mod.rs
This PR fixes #1170.
result Message from `update_key_aliases()` emited [here](https://github.com/wizardsardine/liana/blob/0a7ff2b0ea1b6f4e98946ccc1201a8d1caec8bf5/gui/src/app/state/settings/wallet.rs#L152) was not catch in `SettingState.update()`.
=> gui: update `SettingState.wallet` on `WalletUpdated()` message

src/commands/mod.rs, src/spend.rs, src/testutils.rs, tests/test_chain.py, tests/test_rpc.py
This is to resolve #44.
In the first commit, I combine the destinations and change parameters in `spend::create_spend` in order to avoid "too many arguments" error when adding a new parameter. I think these two parameters combine naturally so that `destinations` includes both recipients and change address.
The second commit sets locktime following the same approach as Bitcoin Core:
- locktime is set to current tip height, but randomly (about 10% of cases) value is set up to 100 blocks earlier
- if tip is more than 8 hours old, locktime is set to 0
For randomness, I'm currently using the current time's milliseconds in order not to add another dependency, which I think is good enough for this use case.
For consistency, I decided to use "locktime" everywhere instead of "lock time" or …
=> spend: randomized anti-fee sniping

src/commands/mod.rs, tests/test_rpc.py
This PR adds the minimum feerate value into the `TooLowFeerate` error message for additional context. Addresses the second bullet point in #853.
=> Add minimum feerate to TooLowFeerate error message

gui/ui/src/component/amount.rs
This PR attempts to address #962, refactoring the amount component to support an internationalized display format and fixing a bug where the integer portion of the decimal didn't support the space separator for BTC values.
I'm attempting to learn Rust, Bitcoin programming, the `iced` GUI library and the Liana stack simultaneously, so this took altogether waaaaay too long, but it ended up being a great onboarding task to start wrapping my head around Rust strings, Strings, slices, vectors, iterators, and rummaging around in the documentation. That said, there are probably plenty of small details or oversights, so pile on the feedback. Here are a few review topics of interest:
* It didn't make sense to me at first that `split_digits()` was responsible for adding GUI rows and formatting …
=> GUI: Add space separator to integer portion of BTC amount rendering

gui/ui/src/component/amount.rs
This PR is based on #1182 and aims to actually refactor the amount component while adding a space separator to the integer portion of BTC amount displays as per #962.
The code organization is reworked to try and separate the conversion of `bitcoin::Amount` type to a `iced` renderable `Row` elements in steps via smaller functions by:
1. Converting the `Amount` type to a string with the integer and fraction portions formatted in space-separated three digit chunks.
2. Detecting where in that string the non-zero BTC amount occurs
3. Converting the string into parts and rendering the preceding zeros and spaces with normal styling while applying a bold `Row` render element for the significant amount.
To me, this approach makes the code easier to read and is a small step toward separating the …
=> GUI: Refactor amount formatting

gui/ui/src/component/amount.rs
This PR attempts to address #1218 by removing extra spacing for amount rendering and making the default for amounts which don' contain a non-zero character to "0.00000000".
=> GUI: Fix amount rendering

gui/src/main.rs
This PR add the version (major+minor) into the window titlebar, for both installer & wallet.
close #1181
=> gui: add the version in the window title bar

gui/src/main.rs
Detected after Manuel failed to have in cache the correct the refresh token. It was not correctly stored after 1h in the settings file because of the wrong datadir.
=> fix wrong datadir in app cache using remote backend

gui/src/lianalite/client/mod.rs
Remote backend has the auth service credentials.
We rely now uniquely on the following urls:
* https://api.signet.lianalite.com for signet
* https://api.lianalite.com for mainnet
=> Change remote backend server url

gui/src/installer/step/backend.rs, gui/src/lianalite/client/backend/mod.rs, gui/src/lianalite/login.rs, gui/src/main.rs
remote backend supports now also mainnet, we have to load downstream the chosen network.
=> fix hard coded network signet for remote backend

tests/test_framework/utils.py
It turns out that setting both to PIPE would result in stderr not being read for some reason. So follow
https://docs.python.org/3/library/subprocess.html and set stdout to PIPE and stderr to STDOUT.
Tested with a process (electrs) which logs on stderr.
=> qa: pipe stderr to stdout, not PIPE

gui/src/installer/mod.rs
Because Testnet and regtest do not ask user the choice of backend the install panic as the RemoteBackend enum stays to undefined
close #1264
=> Fix RemoteBackend::Undefined panic because of skipped step

gui/src/app/message.rs, gui/src/app/state/mod.rs
After reorg last payments were not removed as the reloading message was handle as an extension of the list.
close #1260
=> Use different msg for reloading or extending history tx list

gui/src/logger.rs
Logs are litterally flooded by `cosmic_text` logs at DEBUG level, this PR filter out this target
=> gui: filter out logs for `cosmic_text`

.cirrus.yml, Cargo.lock, Cargo.toml, contrib/lianad_config_example.toml, doc/USAGE.md, src/bitcoin/d/mod.rs, src/bitcoin/electrum/client.rs, src/bitcoin/electrum/mod.rs, src/bitcoin/electrum/utils.rs, src/bitcoin/electrum/wallet.rs, src/bitcoin/mod.rs, src/bitcoin/poller/looper.rs, src/bitcoin/poller/mod.rs, src/commands/mod.rs, src/config.rs, src/descriptors/mod.rs, src/jsonrpc/api.rs, src/jsonrpc/server.rs, src/lib.rs, src/testutils.rs, tests/fixtures.py, tests/test_chain.py, tests/test_framework/bitcoind.py, tests/test_framework/electrs.py, tests/test_framework/lianad.py, tests/test_framework/utils.py, tests/test_misc.py, tests/test_rpc.py
This is to add the Electrum backend as part of https://github.com/wizardsardine/liana/issues/56#issuecomment-2183063784.
This requires the database to be running version 5 following #1180. The migration from a previous DB version must be done using bitcoind. Thereafter, the daemon can be run using an Electrum backend by replacing the `[bitcoind_config]` section in the daemon.toml config file with:
```
[electrum_config]
addr = "127.0.0.1:50001" # adjust IP:port as required
```
Remaining tasks:
=> Add Electrum backend

gui/src/installer/step/backend.rs
Once the user is connected we redirect him to
the next step in the install process, but
we keep the Connected state in case the user
want to edit email after clicking on Previous
As discussed in #1240
=> installer: Go directly to next step once login

src/bitcoin/electrum/client.rs
This is to resolve https://github.com/wizardsardine/liana/issues/1276.
Tested that this change stops GUI freezing in https://github.com/wizardsardine/liana/pull/1241 when using invalid address in Electrum settings.
=> electrum: check connectivity before creating client

gui/Cargo.lock, gui/Cargo.toml
This async-hwi version has a fix about the
wrong fetched version of the coldcard Q device.
=> bump async-hwi 0.0.23

gui/src/hw.rs, gui/src/installer/mod.rs
Because of flaky connection, we drop the connection list to reconstruct it at each step of the installer
close #1307
=> Reset hws watch list each step of the installer

src/bitcoin/electrum/mod.rs, src/bitcoin/electrum/wallet.rs
The common ancestor is the highest block that is strictly lower than the first change.
When finding the point of change, we can take the first height with any change (including an invalidated block) rather than the first height with a new block, which avoids a loop. The height found in both cases (loop vs no loop) should be almost always the same as we apply the update to our local chain before finding the common ancestor, but perhaps in a test if there's a reorg down to 0 and the chain update only contains invalidated blocks and no new blocks, then checking for the first invalidated block would be better as there would be no new blocks to find and the reorg would be undetected.
=> electrum: common ancestor is before first changed block

src/bitcoin/electrum/client.rs, tests/test_framework/electrs.py
Ping server as an extra connectivity check.
=> electrum: ping server before returning client

.cirrus.yml, src/bitcoin/electrum/mod.rs, tests/test_chain.py
The `from_chain_tip` command takes a `CheckPoint` of our current chain tip for purposes of providing a chain update which connects to it, including in case of a reorg.
This is not a point from which to rescan the chain.
The current code made it so in case a rescan was performed while there was too much progress on the backend (>8 blocks), or when there was a deep enough reorg, the chain update could not unambiguously connect to our local chain. Here is an instance (logs were adapted to debug this issue):
```
2024-09-10T15:19:48.258728Z DEBUG liana::bitcoin::electrum:196: Full local chain: LocalChain { tip: CheckPoint(CPInner { block: BlockId { height: 618, hash: 0x6c6f30d76e1ce1bee2157d271300b93e968c501685c20e8466635310a4622efe }, prev: Some(CPInner { block: BlockId { height: 617, hash: …
```
=> electrum: make sure chain updates connect on rescan

gui/Cargo.lock, gui/src/app/state/settings/bitcoind.rs, gui/src/installer/step/node/electrum.rs, gui/src/node/electrum.rs
This is the first commit from #1303.
=> gui(settings): add sanity check on electrum wallet address

gui/src/app/state/settings/bitcoind.rs
In case of error reloading daemon for Electrum, set edited to false (same handling as for bitcoind).
=> gui(settings): fix daemon reload handling for electrum

gui/src/lianalite/client/backend/api.rs, gui/src/lianalite/client/backend/mod.rs
Instead of having an unclear and ugly message like:
data did not match any variant of untagged enum DraftPsbtResult
=> Deserialize error from create_spend http response

src/commands/mod.rs, src/spend.rs, tests/test_spend.py
This is a quick change to address #1322.
It adds 10 sats to the fee for a non-replacement transaction targeted at 1 sat/vb.
=> spend: ensure fee above min relay value

gui/src/app/view/settings.rs
=> backport for v7: fix wrong redirection message in settings

src/bitcoin/poller/looper.rs
This fixes a crash whereby we missed the deposit transaction of a received coin because it was also part of the expired coins list.
See the following logs.
```
[8:33 AM](https://mm.revault.dev/revault/pl/a9mazcncaff3fc88yq8oqpipgo)
root@cirrus-ci-task-4780461782728704:/tmp/cirrus-ci-build# tail -n100 /tmp/lianad-tests-o3guj0vh/test_rescan_edge_cases_1/
lianad/log 
b'[1726295509][liana][INFO][thread main] Watchonly wallet created.'
b'[1726295509][liana][INFO][thread main] Loading our watchonly wallet on bitcoind.'
b'[1726295509][liana][INFO][thread main] Watchonly wallet loaded on bitcoind and sanity checked.'
b'[1726295510][liana::database::sqlite][INFO][thread main] Created a fresh database at /tmp/lianad-tests-o3guj0vh/test_rescan_edge_cases_1/lianad/regtest/lianad.sqlite3.' …
```
=> poller: query deposit tx for all coins, including expired

src/bitcoin/poller/looper.rs
=> v7: backport #1338

gui/src/app/view/settings.rs, gui/src/installer/view.rs, gui/src/node/electrum.rs
This adds a short text explanation about SSL usage in Electrum addresses to both the installer and settings page.
This is a modified version of #1342.
=> gui: add help text for electrum address

gui/src/app/view/settings.rs, gui/src/installer/view.rs, gui/src/node/electrum.rs
=> backport for v7: gui: add help text for electrum address

gui/src/app/view/hw.rs, gui/src/hw.rs, gui/src/installer/view.rs, gui/ui/src/component/hw.rs
=> Check coldcard version and request user to upgrade

gui/src/app/state/mod.rs, gui/src/app/state/transactions.rs, gui/src/app/view/home.rs, gui/src/app/view/transactions.rs
The problem:
We display the button if the size of the list is a multiple of the page size. Otherwise, we assume that the user has reached a partial page, indicating they've reached the bottom. However, since we chose to include all transactions with the same block time on a single page (because it's not possible to order them by block index in the database, as we don't store the block index), this can cause the page size to exceed the set limit. As a result, the list size may not be a multiple of the page size.
The solution:
keep in the state if the last fetched page has a length inferior of the expected page size and do not display the button 'See more' then as we reached the bottom.
=> fix history events and txs pagination

gui/src/hw.rs
We check if we are able to fetch master fingerprint to see if the bitcoin app is open. The error is then displayed with the generic connection error message.
=> hw: check if app is open before sending old version error message

gui/src/app/view/coins.rs, gui/src/app/view/home.rs, gui/src/app/view/label.rs, gui/src/app/view/mod.rs, gui/src/app/view/psbt.rs, gui/src/app/view/psbts.rs, gui/src/app/view/receive.rs, gui/src/app/view/recovery.rs, gui/src/app/view/settings.rs, gui/src/app/view/spend/mod.rs, gui/src/app/view/transactions.rs, gui/src/installer/view.rs, gui/src/launcher.rs, gui/src/lianalite/login.rs, gui/src/loader.rs, gui/ui/src/theme.rs
close #1380
We removed all the primary buttons, they will be introduced back in the GUI incrementally to follow a one primary button per page policy
The secondary button is border grey then border and text green on hover, whereas primary button will have its background green to be a call to action to the user.
The background of the secondary button is changed for a light grey in order to be consistent with items list selection.
=> Change primary and secondary button for consistency

gui/src/app/cache.rs, gui/src/app/message.rs, gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/view/home.rs, gui/ui/src/component/amount.rs, gui/ui/src/component/mod.rs, gui/ui/src/component/spinner.rs
This is to resolve #1361.
The home page considers the wallet to be syncing if its height is 0. In this case, the balance will slowly blink and a "Syncing..." text will appear just below.
The home page will check the wallet's height upon each cache refresh, and will reload the home page once the syncing has completed so that the updated balance is displayed without the user needing to do anything.
Both the blinking balance and "Syncing..." text use a new `Carousel` widget that cycles through different child widgets at a specified rate.
EDIT: I've added an extra commit to address #1363 as that is also related to the wallet height and cache refresh.
=> [GUI] Indicate wallet is syncing after completing installer

gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/state/settings/mod.rs, gui/src/daemon/embedded.rs, gui/src/daemon/mod.rs, gui/src/loader.rs, gui/src/node/mod.rs
This is a follow-up to #1370.
If the user has imported a descriptor and is using bitcoind as a local node, then they will need to perform a rescan in order 
to see past transactions. Treating the wallet as syncing in this case could mislead the user that a rescan is being performed. Therefore, it's better to keep the past behaviour here to avoid further confusion.
=> [GUI] Don't treat wallets using bitcoind as syncing

src/bitcoin/electrum/mod.rs
These sync messages appear typically every 30 seconds and are only useful for debugging purposes.
The full scan messages can remain at info level for now as they are only expected to occur once for a new wallet and then only in case a rescan is performed.
=> electrum: use debug log level for sync messages

doc/API.md, src/bitcoin/poller/looper.rs, src/bitcoin/poller/mod.rs, src/commands/mod.rs, src/database/mod.rs, src/database/sqlite/mod.rs, src/database/sqlite/schema.rs, src/database/sqlite/utils.rs, src/testutils.rs, tests/test_framework/lianad.py, tests/test_rpc.py
This is a first step towards #1373.
The timestamp of the last completed poll of the blockchain will be stored in the database, and this value will be made available via the `getinfo` command.
=> Get timestamp of last completed poll of the blockchain

gui/Cargo.lock, gui/src/app/cache.rs, gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/view/home.rs, gui/src/lianalite/client/backend/mod.rs, gui/src/loader.rs, gui/src/main.rs
This PR uses the changes from #1376 to complete #1373.
It builds on the changes from #1370 to consider an existing wallet (that uses a local backend) to be syncing until the first poll completes after opening the GUI, where "existing wallet" means one that has positive height (since a newly created wallet has height 0).
Note that for an external Liana daemon,  this logic is only applied in case the last poll timestamp has already been set when starting the GUI. Otherwise, we can't be sure if this external daemon will ever set this value.
=> [GUI] Consider wallet to be syncing until first poll completes after opening

gui/src/node/bitcoind.rs
This is to resolve #1372.
Hashes were taken from https://bitcoincore.org/bin/bitcoin-core-28.0/SHA256SUMS.
File names we use can be found here:
https://github.com/wizardsardine/liana/blob/2d5991cb0cf4a2017879aa76175cac7745e13790/gui/src/node/bitcoind.rs#L42-L60
=> gui: upgrade managed bitcoind version to 28.0

gui/src/installer/view/editor/mod.rs, gui/src/installer/view/editor/template/multisig_security_wallet.rs
The primary keys shouldn't be editable from the recovery path in the Multisig Savings template but only from the primary path. It could bring to weird behaviors and corner cases.
=> Disable edit of defined key in multisig template recovery path

gui/src/installer/view/mod.rs
This Next button was accidentally removed in commit bd03cc9cfffb7c5c45dd0dd60d54db807d4e02a2.
=> gui(installer): re-add next button when starting managed bitcoind

.github/workflows/main.yml, contrib/reproducible/docker/macos.Dockerfile, contrib/reproducible/docker/macos_cmd.sh, contrib/reproducible/docker/windows.Dockerfile, contrib/reproducible/docker/windows_cmd.sh, contrib/reproducible/guix/manifest.scm, doc/BUILD.md, gui/Cargo.lock, gui/Cargo.toml
This PR updates our build system to use rust 1.71.1, required by the last version of async-hwi
=> bump gui msrv to 1.71.1

gui/src/app/state/psbt.rs, gui/src/hw.rs
This PR is build on top of #1357, with few adds:
- get the version from bitbox device
- check the version for taproot support
- copy `tap_script_signs` & `tap_key_sig` if present in the pruned psbt after signature
Tested spending by internal key & taptree w/ differents setups
~~Note: this PR use `bitbox-tapminiscript` branch of `async-hwi`~~
=> gui: add support for tapminiscript on bitbox02

gui/src/app/cache.rs, gui/src/app/mod.rs, gui/src/app/state/mod.rs, gui/src/app/wallet.rs, gui/src/loader.rs, gui/src/main.rs
This is to resolve #1414.
In the end, I felt it was simple enough to include commits that cover both parts of #1414 (the short-term change and the follow-up).
I start with the short-term change (setting the refresh interval ignoring the last poll logic) and then follow with commits that cover all syncing statuses.
I don't use as high a refresh frequency for a remote backend as for a local backend, but these values can be easily changed if required.
=> Refresh cache more often in GUI while wallet or blockchain is syncing

gui/src/installer/view/editor/template/custom.rs, gui/src/installer/view/editor/template/inheritance.rs, gui/src/installer/view/editor/template/multisig_security_wallet.rs, gui/src/installer/view/mod.rs
This is to fix #1410, including for the mnemonic and descriptor backup steps.
The space height in all cases will be 70.0 when combined with the existing vertical spacing between elements.
=> gui(installer): add space at bottom of pages

gui/src/installer/view/editor/template/custom.rs, gui/src/installer/view/editor/template/inheritance.rs, gui/src/installer/view/editor/template/multisig_security_wallet.rs, gui/src/installer/view/mod.rs
- replace this warning:
by this one:
- before if a non tap miniscript compatible device was selected, the selected icon was displayed, now the warning icon have priority:
=> gui(installer): better warn. if a signer is not compatible w/ tapminiscript

gui/src/installer/view/editor/mod.rs
This is to fix #1402 following the suggestion in https://github.com/wizardsardine/liana/issues/1402#issuecomment-2448730840.
=> gui(installer): make edit key modal scrollable

gui/src/installer/view/editor/mod.rs
=> gui(installer): align title & descrpition in path cards

contrib/release/release.sh
Arch package failed to be extracted during pacman update because of the default zstd algo
=> Add compression algo flag to dpkg command for arch build

gui/src/installer/view/mod.rs
=> gui(installer): fix word plurality when adding keys

gui/src/installer/view/mod.rs
=> backport for v8: #1441: gui(installer): fix word plurality when adding keys

gui/src/installer/view/mod.rs
This is to fix #1439. It follows the same approach as used in the settings to ensure consistent ordering when iterating over keys.
=> gui(installer): use fixed keys ordering

gui/src/installer/view/mod.rs
=> gui(installer): list wallets using secondary buttons

gui/src/installer/view/mod.rs
=> gui(installer): fix typo in remote backend description

src/commands/mod.rs, src/descriptors/mod.rs, src/spend.rs, tests/fixtures.py, tests/test_spend.py
This is a fix to #1371 and the related #1322.
As per https://github.com/wizardsardine/liana/issues/1371#issuecomment-2446921093, this adds the varint length for the script and control block elements of a Taproot primary path spend.
I think this is what caused #1322 and so I have reverted the change from #1323.
=> descriptors: fix max satisfaction weight for Taproot multisig primary path spends

liana-gui/src/app/view/spend/mod.rs, liana-ui/src/component/amount.rs
=> gui(send): display max calculated amount w/ 8 decimals

liana-gui/src/app/state/mod.rs, liana-gui/src/app/wallet.rs
Following #1386, this PR will show past payments on the home page while the blockchain is still syncing. Currently, these are not loaded until the wallet has finished syncing.
This change won't apply if the wallet itself is still syncing. The reason is that this is not expected to take so long and so it's better to wait for the updated data. Furthermore, the DB may be locked if the poller is running, in which case we wouldn't be able to load past transactions until the wallet has synced anyway. The home page reloads automatically as soon as the wallet finishes syncing.
=> gui: reload home if wallet is not syncing

doc/USAGE.md
PR fixes the broken references found in the `doc/USAGE.md` file.
=> Update usage references

liana/src/descriptors/mod.rs
This fixes #1406, building on the fix from #1451 for estimating the weight of each input.
An extra 2 is added to the unsigned transaction's weight to account for the Segwit marker and flag.
=> descriptors: fix unsigned tx max satisfaction weight

tests/test_framework/utils.py
=> tests: notifyAll() is deprecated, replace w/ notify_all()

doc/API.md, liana-gui/src/app/state/coins.rs, liana-gui/src/app/state/psbt.rs, liana-gui/src/lianalite/client/backend/mod.rs, lianad/src/bitcoin/poller/looper.rs, lianad/src/commands/mod.rs, lianad/src/database/mod.rs, lianad/src/database/sqlite/mod.rs, lianad/src/database/sqlite/schema.rs, lianad/src/database/sqlite/utils.rs, lianad/src/testutils.rs, tests/test_chain.py, tests/test_misc.py, tests/test_rpc.py
:warning: This PR upgrades and migrates DB version so a wallet opened against this PR will no longer work on Liana v8.
This is a first step towards #1375.
Following the approach from #1391, this PR adds a new `is_from_self` field to the response of the `listcoins` command.
The underlying information is stored in a new `is_from_self` column in the coins database table. This column could instead have been added to the transactions table, but for consistency with other transaction-related columns, I added it to the coins table. It's also important to note that being from self is wallet-dependent, so adding it to the transactions table would not work if multiple wallets were supported in the same DB (h/t edouardparis).
A subsequent PR will then use this field in the GUI to determine which …
=> commands: indicate in `listcoins` response whether coin is from self

contrib/release/release.sh, contrib/reproducible/guix/build.sh, contrib/reproducible/guix/guix-build.sh, contrib/reproducible/guix/manifest.scm
Zig language has solved many issues regarding compilation linker.
It allows us to compile to a smaller version of glibc while using latest guix commit.
No need then to bootstrap multiple version of rust, the current supported version is 1.71.1
close #414
=> Use cargo-zigbuild for reproducible build with glibc 2.31

liana-gui/src/app/view/coins.rs, liana-gui/src/app/view/spend/mod.rs, liana-gui/src/installer/mod.rs
=> chore: fix some comments

lianad/src/commands/mod.rs, tests/test_spend.py
This is to resolve #1484.
We previously used unconfirmed change for coin selection as a best-guess way of identifying those unconfirmed coins from self, but now we have the `is_from_self` field we can use it directly and be sure we only select coins that are fully under our control.
=> commands: use unconfirmed coins from self for coin selection

.github/workflows/main.yml, contrib/reproducible/guix/manifest.scm, doc/BUILD.md, rust-toolchain.toml
The update of the reproducible system allow us to bump the minimal rust supported version. Although bumping a MSRV should be conservative, it is a requirement for us if we want to be able to support last https://github.com/iced-rs/iced version and improve the experience of our users.
=> bump msrv 1.80

liana-gui/src/app/state/settings/bitcoind.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/settings.rs
=> gui(settings): add a button to copy auth fields & mask password

Cargo.lock, liana-gui/Cargo.toml, liana-gui/src/app/message.rs, liana-gui/src/app/state/export.rs, liana-gui/src/app/state/mod.rs, liana-gui/src/app/state/transactions.rs, liana-gui/src/app/view/export.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/mod.rs, liana-gui/src/app/view/transactions.rs, liana-gui/src/export.rs, liana-gui/src/lib.rs
This PR add a feature to export transactions:
Done:
=> gui: tx export feature

.github/workflows/main.yml, Cargo.lock, contrib/lianad_config_example.toml, liana-gui/src/app/state/settings/bitcoind.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/settings.rs, liana-gui/src/installer/message.rs, liana-gui/src/installer/step/node/electrum.rs, liana-gui/src/installer/view/mod.rs, liana-gui/src/node/electrum.rs, lianad/Cargo.toml, lianad/src/bitcoin/electrum/client.rs, lianad/src/config.rs
closes #1300 
The issue about connecting to an electrum certificate using `rustls` have been fixed [upstream](https://github.com/bitcoindevkit/bdk/issues/1598) but in order to beneficiate from it we have to update `bdk_electrum` and `rust-bitvoin` dependencies.
Meanwhile, this PR introduce a workaround: the initial issue is related to `electrum-client` `use-rustls` feature and `use-openssl` feature is not reexported by `bdk_electrum` but we can use `electrum-client` crate directly and use `use-openssl` feature by this way:
Note: ssl://testnet.aranguren.org:51002 electrum server can be used to test this PR
=> gui: allow to connect to an electrum server w/ a self signed certificate

liana-gui/src/export.rs
This PR replace the fee displayed as 0 by a blank.
=> export transactions: output a blank if fee is 0

liana-gui/src/daemon/model.rs
This is a follow-up to #1503 to fix an issue with change outputs appearing as outgoing payments on the home page.
It expands the definition of `PaymentKind::SendToSelf` to include change outputs since these are also payments to self.
=> fix: treat change outputs as send-to-self payments

.github/workflows/main.yml, Cargo.lock, contrib/lianad_config_example.toml, liana-gui/src/app/state/settings/bitcoind.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/settings.rs, liana-gui/src/installer/message.rs, liana-gui/src/installer/step/node/electrum.rs, liana-gui/src/installer/view/mod.rs, liana-gui/src/node/electrum.rs, lianad/Cargo.toml, lianad/src/bitcoin/electrum/client.rs, lianad/src/config.rs
This reverts commit 2d2d080888f5c2a0fd82d6c4a4009a254b2dbcb2, reversing changes made to cfe15b360d0f9a40d0de2ca00bdd1530e6e6c8e9.
We are not ready yet to have openssl dynamically link library dependency for our users.
=> Revert "Merge #1500: gui: allow to connect to an electrum server self signed certificate

liana-gui/src/daemon/model.rs
This is a follow-up fix to #1507.
Only those change outputs from outgoing transactions should be considered send-to-self payments.
=> fix: send-to-self payments should only include change outputs from outgoing transactions

liana-gui/src/app/view/export.rs, liana-gui/src/app/view/transactions.rs, liana-gui/src/export.rs
The default file name has been changed to "liana-txs-{date}.csv", e.g. "liana-txs-2025-01-03T10-03-39.csv".
I also changed the "Export" button to use a helper as suggested by edouardparis.
=> [GUI] Change default file name for transactions export

liana-gui/src/app/view/export.rs
This reverts commit 98195e03b6878cd31e1d34ba246700b6ae95ceb1.
The progress bar can disappear too quickly.
=> Revert 'hide progress bar once export completed'

liana-gui/src/app/state/psbt.rs
While testing #1513, it became apparent that Taproot signatures were not being merged properly when updating a PSBT.
This PR fixes and refactors the code to use the `merge_signatures` function that contains the required logic.
=> fix: merge Taproot sigs when updating PSBT

liana-gui/src/app/state/psbts.rs
=> fix reload of selected psbt after update

lianad/src/database/sqlite/mod.rs, lianad/src/lib.rs
While directly migrating from v7 to v9, the daemon get a problem and panic because it was using the db_coins query with v9 coins columns.
=> fix fetching of coins txids before migration

lianad/src/database/sqlite/mod.rs, lianad/src/lib.rs
=> backport: fix fetching of coins txids before migration

liana-gui/src/app/message.rs, liana-gui/src/app/mod.rs, liana-gui/src/app/state/mod.rs, liana-gui/src/app/state/settings/bitcoind.rs
This is to fix #1528.
It updates the `processing` field of the rescan settings each time the cache is updated.
=> Fix update of rescan state upon completion

liana-gui/src/export.rs
=> export: list transaction in chronological order

contrib/release/release.sh
The zip was containing only the readme file and the unsigned .exe. It is not really useful for a windows user.
=> release: remove windows zip

contrib/release/release.sh, contrib/release/sign.sh
* Use LIANA_PREFIX var everywhere
* Remove capital letter from macos binaries.
* Add macos to .zip title
=> fix release and sign scripts

liana/src/descriptors/analysis.rs, liana/src/descriptors/mod.rs
This allows to create a new `LianaPolicy` without checking that it compiles into miniscript. This compilation check is used as a sanity check on the policy in addition to other Liana-specific checks, but this compiled policy is not otherwise used.
When parsing an existing descriptor, we will assume that the policy can be compiled. Otherwise, the method `LianaPolicy::from_multipath_descriptor` ends up calling `LianaPolicy::into_multipath_descriptor_fallible`.
A `LianaPolicy` is created from a descriptor each time we call `LianaDescriptor::from_str`, which is done often, e.g. when updating derivation indices in the DB. Removing the compilation check won't affect the `LianaDescriptor` that we end up with when parsing a string as we already use the `Descriptor` obtained from parsing the …
=> skip policy compilation when parsing descriptor

.cirrus.yml
This will reduce some of the overhead of setting up each task.
=> ci: reduce number of tasks

doc/API.md, lianad/src/commands/mod.rs, tests/test_rpc.py
This is to fix #854 when using a local node. If we don't have the PSBT saved in our DB, we query the wallet transaction instead.
The Liana Connect backend will also need to be updated in a similar way.
=> Allow RBF without saved PSBT

.cirrus.yml
=> ci: use bitcoind version 28.1

liana-gui/src/app/state/mod.rs, liana-gui/src/app/state/spend/step.rs, liana-gui/src/daemon/model.rs
This is to resolve #1326. In case of insufficient funds when creating a spend, the selected coins will be updated to correspond to the missing amount. Previously, no changes were made to selected coins.
Furthermore, if a user selects the max option for a recipient, only owned coins (confirmed or unconfirmed from self) will be considered rather than all coins, since unconfirmed coins that are not from self should only be used if the user has selected them manually.
=> [GUI] Improve coin selection logic when creating spend

Cargo.lock, liana-ui/Cargo.toml, liana-ui/src/component/form.rs, liana-ui/src/lib.rs, liana-ui/src/theme/overlay.rs, liana-ui/src/widget/cursor.rs, liana-ui/src/widget/editor.rs, liana-ui/src/widget/menu.rs, liana-ui/src/widget/mod.rs, liana-ui/src/widget/text_input.rs
We add an overlay to the fork of the text_input widget to display "Paste" when user clicks on Right click.
When a text is selected, the button Copy is added to the overlay choices.
=> Add copy paste overlay buttons to text_input

Cargo.lock, contrib/reproducible/guix/build.sh, lianad/Cargo.toml
This uses a modified version of bdk_electrum 0.15 (corresponding to BDK tag v1.0.0-alpha.13) that enables the use of the ring provider in rustls.
The default aws-lc-rs provider breaks the reproducible build.
=> use ring provider with rustls in electrum client

liana-gui/src/app/settings.rs, liana-gui/src/app/state/settings/wallet.rs, liana-gui/src/app/view/settings.rs, liana-gui/src/app/wallet.rs, liana-gui/src/installer/context.rs, liana-gui/src/installer/descriptor.rs, liana-gui/src/installer/message.rs, liana-gui/src/installer/mod.rs, liana-gui/src/installer/step/descriptor/editor/key.rs, liana-gui/src/installer/step/descriptor/editor/mod.rs, liana-gui/src/installer/step/descriptor/mod.rs, liana-gui/src/installer/step/mod.rs, liana-gui/src/installer/view/editor/mod.rs, liana-gui/src/installer/view/editor/template/custom.rs, liana-gui/src/installer/view/editor/template/inheritance.rs, liana-gui/src/installer/view/editor/template/multisig_security_wallet.rs, liana-gui/src/installer/view/mod.rs, liana-gui/src/lianalite/client/backend/api.rs, liana-gui/src/lianalite/client/backend/mod.rs, liana-gui/src/lib.rs, liana-gui/src/main.rs, liana-gui/src/services/api.rs, liana-gui/src/services/mod.rs, liana-ui/src/component/form.rs, liana-ui/src/component/hw.rs
This PR implements #1578 and #1579.
Please note the following:
- I've left the cosigner option enabled for initial testing as part of this PR, but will disable it afterwards (#1584 ).
- Using cosigner keys is currently possible in all templates, including the Simple Inheritance template, but given that there is only one key per path in this template, it would not be possible to continue with a cosigner key selected. I could disable the option to select cosigner keys in this template in a follow-up PR, but in any case there will be a warning so the user will be aware of the problem.
- Safety net paths can only be added in the Custom template for now.
- ~~This cannot yet be tested with Liana Connect.~~ Can be tested on Signet with Liana Connect.
- ~~The URL for fetching & redeeming keys is …
=> Fetch and redeem provider keys using tokens

liana-gui/src/installer/step/descriptor/editor/key.rs
This simplifies the warning message for the user in case a fetched provider key (more precisely, any key with the same fingerprint) has already been added to the wallet (as a different key kind).
=> Reword warning for non-unique provider key kind

liana-gui/src/app/view/settings.rs
Use consistent case in the settings:
- "Import/Export" for the section card to match the header on the corresponding page. The choice is to capitalise both words as the slash indicates either word could be treated as a title by itself.
- Use "Back up wallet" to match the case of the other options on that page.
=> gui(settings): use consistent case

liana-gui/src/installer/descriptor.rs
This resolves #1584 by disabling cosigner keys in the installer.
=> gui(installer): disable cosigner keys

lianad/src/commands/mod.rs, lianad/src/database/mod.rs, tests/test_rpc.py, tests/test_spend.py
This is to fix #1591.
The database should store the last used/revealed derivation index:
- Docstrings have been updated accordingly.
- Getting a new address requires that the database value first be incremented.
- When listing addresses without specifying a count, all used/revealed addresses should be returned.
=> Ensure consistent derivation index management

lianad/src/commands/mod.rs, lianad/src/database/mod.rs, tests/test_rpc.py, tests/test_spend.py
The database should store the last used/revealed derivation index.
Docstrings have been updated accordingly.
Getting a new address requires that the database value first be incremented.
When listing addresses without specifying a count, all used/revealed addresses should be returned.
backport of #1605
=> lianad: ensure consistent derivation index management

liana-gui/src/app/menu.rs, liana-gui/src/app/mod.rs, liana-gui/src/app/state/mod.rs, liana-gui/src/app/view/home.rs, liana-gui/src/app/view/message.rs, liana-gui/src/daemon/mod.rs, liana-gui/src/loader.rs, liana-gui/src/main.rs
This adds a warning on the home page if the wallet has been restored from a backup and the user is using a local bitcoind node.
This warning has a button to jump to the rescan page and another button to dismiss the warning, which is the only way to remove it (rescanning does not automatically remove it).
Whether the wallet was restored from a backup is not saved after closing the GUI, so this warning will only be shown in the same user session as that in which the wallet was restored.
The warning will not currently be shown when importing a descriptor.
=> show rescan warning after restoring wallet from backup

liana-gui/src/installer/step/descriptor/editor/key.rs, liana-gui/src/installer/view/editor/mod.rs
This fixes a regression introduced as part of the key-from-token work for cosigner and Safety Net keys.
The manually entered xpub should continue to be displayed until the "Apply" button has been clicked and the changes saved.
The `chosen_key_source_kind` field has been renamed to `form_key_source_kind` as it is only used to determine which of the xpub and token forms should be displayed. Its value is now only set to `Some` when the form for entering an xpub or token should be displayed. This change allows to distinguish between a manual xpub that has just been entered in the form and one that was previously entered and has been chosen from the list of existing keys.
=> gui(installer): show manually entered xpub in modal until saved

liana-gui/src/app/state/recovery.rs
This is to fix #1636 and consequently fixes #1102. This PR therefore replaces #1144.
A wallet containing an unconfirmed coin of timelock 1 will no longer show any recovery paths as available.
The recovery transaction created by `createrecovery` only includes confirmed coins and so we should only consider these coins when checking for available recovery paths. An unconfirmed coin could not be broadcast in a recovery transaction as it would not yet satisfy the timelock constraint.
=> filter for confirmed coins when checking recovery paths

liana-gui/src/app/cache.rs, liana-gui/src/app/mod.rs, liana-gui/src/lianalite/login.rs, liana-gui/src/loader.rs, liana-gui/src/main.rs
With this PR, coins will be cached when first loading a GUI that is using Liana Connect as the backend.
The cache refreshes less often for Liana Connect (every 2 mins), which means there can be a discrepancy between the coins loaded on a page and those in the cache, especially when first loading the GUI with no coins cached.
This can be seen when choosing to refresh a coin in the Coins panel. After selecting the coin and the refresh option, the Self-Send page is displayed with coins listed, but the coin that was previously selected in the Coins panel won't be selected here unless the cache has already refreshed. By caching coins at the start, it makes such a scenario less likely to occur when using Liana Connect.
=> fix: cache coins when first loading GUI with Liana Connect

liana-gui/src/app/config.rs, liana-gui/src/app/mod.rs, liana-gui/src/installer/mod.rs, liana-gui/src/launcher.rs, liana-gui/src/loader.rs, liana-gui/src/main.rs
This commit is part of preparatory work to support multiple wallets.
This commit introduces two breaking change:
The fields daemon_config_path and daemon_rpc_path are removed. The GUI will deduce these values from their expected location in the root data directory.
Because this link is removed, the gui flag --conf is not useful anymore as it cannot then find the location of the root data directory.
=> Remove the link between gui config and lianad config

liana-gui/src/backup.rs, liana-gui/src/export.rs, liana-gui/src/installer/context.rs, liana-gui/src/installer/mod.rs, liana-gui/src/installer/step/node/bitcoind.rs, liana-gui/src/main.rs, lianad/src/bin/cli.rs, lianad/src/config.rs, lianad/src/datadir.rs, lianad/src/lib.rs, lianad/src/testutils.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_misc.py
A new field data_directory is introduced in lianad configuration, it resolves directly to the path of the wallet datadir without the per network reasoning. The previous data_dir field is kept for backward compatibility for already generated configuration file.
=> Prepare datadir for multiple wallet support

liana-gui/src/app/state/spend/mod.rs, liana-gui/src/app/state/spend/step.rs
This fixes one of the items from #1664, but it's a little different from the other items there so I felt a separate PR would be better.
This fixes an issue for the Recovery panel that was introduced by #1658, but which was already present in the Send panel. If, while creating a regular spend, the user edits the fingerprint aliases, these updated aliases would not have shown in the signing info of the draft PSBT. For a recovery, this issue arises on the first step when selecting a recovery path, where the aliases are shown for each key required on that path.
The issue arises because the `wallet` field of individual steps was not being updated.
Now, the `wallet` will be stored by `CreateSpendPanel` and used by `load()` when moving between steps. Furthermore, the `WalletUpdated` message will …
=> fix: ensure spend (& recovery) panel steps use latest fingerprint aliases

doc/API.md, lianad/src/commands/mod.rs, lianad/src/jsonrpc/api.rs, lianad/src/testutils.rs, tests/fixtures.py, tests/test_framework/lianad.py, tests/test_rpc.py
This implements #1678.
The command parameters differ slightly from those described in the issue:
- instead of a `keychain` enum parameter, I used  `is_change` to control whether receive or change addresses are returned.
- I used an optional `continue_from` parameter to control pagination. The value to pass in the next request is provided by the previous response. If no value is provided in the response, there are no more addresses to list. If no value is set in the request, the addresses will be returned starting from the last revealed address.
Setting the positional argument for `continue_after` as `null` will be treated the same as omitting it (for other RPC commands, a `null` value results in a parsing error).
=> feat: add `listrevealedaddresses` command

liana-gui/src/app/state/psbt.rs, liana-gui/src/app/view/hw.rs, liana-gui/src/app/view/psbt.rs, liana-gui/src/daemon/model.rs, liana-ui/src/component/hw.rs, liana/src/descriptors/analysis.rs, liana/src/descriptors/mod.rs
Inspired by #1607 this shoud closes #1041.
Notice that I added the wanted logic also for the recovery spending. That means you can only select a signing device related to the primary path for usual spend. But for recovery spending you can only select a signing device related to the recovery_path.
You can see here both examples :
=> Disable signing devices that should not or cannot spend

liana-gui/src/app/mod.rs, liana-gui/src/app/settings.rs, liana-gui/src/app/state/settings/wallet.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/settings.rs, liana-gui/src/app/wallet.rs, liana-gui/src/daemon/mod.rs, liana-gui/src/installer/context.rs, liana-gui/src/installer/message.rs, liana-gui/src/installer/mod.rs, liana-gui/src/installer/step/backend.rs, liana-gui/src/installer/step/mod.rs, liana-gui/src/installer/step/wallet_alias.rs, liana-gui/src/installer/view/mod.rs, liana-gui/src/launcher.rs, liana-gui/src/main.rs, liana-gui/src/services/connect/client/backend/api.rs, liana-gui/src/services/connect/client/backend/mod.rs, liana-gui/src/services/connect/login.rs
We had a new `wallet_alias` to settings file.
This field is displayed in the launcher when wallets are listed and in the window title when the app is running the wallet.
The field is also store in liana-connect wallet.metadata field to facilitate import of wallet from Liana-Connect.
If the field was modified on Liana-Connect, then next time the user open the wallet in the gui, the settings field is updated.
User can modify the wallet alias in the Settings > Wallet section.
=> Update wallet alias

liana-gui/src/app/state/export.rs, liana-gui/src/app/state/settings/mod.rs, liana-gui/src/app/state/settings/wallet.rs, liana-gui/src/app/view/export.rs, liana-gui/src/export.rs
We pass the wallet to the import_backup method
so the wallet id is used to find the correct wallet settings to update in the settings file.
=> fix import backup for existing wallet

liana-gui/src/app/view/settings.rs
This fixes an issue when viewing a long node setting value, such as the cookie path, on a reduced window size.
=> fix: use scrollbar for node settings

liana-gui/src/app/state/settings/mod.rs, liana-gui/src/app/state/settings/wallet.rs
While restoring a backup at the import/export panel, the message to update the wallet keys aliases was not handled and although the aliases are stored in the settings file, the wallet was not "reloaded" through the Message::WalletUpdated result. The consequence was while opening the wallet section, users found the aliases not updated by the backup (even if the file was updated).
The change in the update_aliases is to update the wallet alias only if the function require the change by passing
`Some(alias)` in arg.
=> fix settings: missing update_aliases for backup restore

liana-gui/src/backup.rs, liana-gui/src/installer/mod.rs, liana-gui/src/installer/step/descriptor/mod.rs, liana-gui/src/installer/step/wallet_alias.rs
- We add a default wallet alias if not value is set in the installer context.
- We add the wallet alias field to the backup file. 
- While importing a backup in the installer, the backup wallet alias will be suggested to the user at the final step. 
- While importing a backup in the wallet settings for an already installed wallet, we keep the current wallet alias and not override it by the backup one.
=> Apply backup alias when importing backup in installer.

liana-gui/src/app/view/receive.rs
To avoid the need for a scrollbar when showing previous addresses in the collapsed view, we will now show the first and last 16 characters only.
=> show partial address in collapsed view

liana-gui/src/app/state/psbt.rs, liana-gui/src/app/state/spend/step.rs, liana-gui/src/app/view/psbt.rs, liana-gui/src/app/view/spend/mod.rs
This Pr is to mitigate three issues:
close #1719 
close #1685
and try to prevent a little bit the problem of impossible cancellation of the signing Task by disabling any other buttons and making aware of the user that he has to finish it (reject of approve).
Sadly it is not the case for the sidebar menu button, so if user start the signing process and quit by switching panel, he may still have the problem of the signing task blocking in the background and may be surprised by the impossibility of iced to close properly.
Proper signing task cancellation will require a change in the async-hwi library: https://github.com/wizardsardine/async-hwi/issues/108
=> Make user finish signing process before opening new modal

liana-gui/src/app/state/settings/wallet.rs
L522 the wallet was populated with its new alias
and the check L567 was always false.
wallet_alias is None if we do not have to update it, so better pass the variable directly.
=> fix update wallet alias in wallet settings

liana-gui/src/app/mod.rs
This fixes #1743 by using the correct daemon config file path of the current wallet.
=> fix: use correct path to daemon.toml in settings

liana-gui/Cargo.toml
tiny-skia is an other renderer that does not
rely on wgpu. Iced uses it as a fallback in case
of wgpu problems.
The feature can be tested with:
`ICED_BACKEND=tiny-skia cargo run --release --bin liana-gui`
close #1676
=> Add tiny-skia feature to iced dep

liana-gui/src/installer/view/editor/mod.rs, liana-gui/src/installer/view/mod.rs
The first commit adds monthly steps to the timelock selection slider and adapts time estimation precision.
The second is a tiny GUI improvement.
Here few examples :
=> Improve timelock duration selection and display

liana-gui/src/launcher.rs
This is a follow-up to #1746 to address the case where the wallet uses Liana Connect, in which case `start_internal_bitcoind` is set to `null` in the settings file.
=> fix: a wallet with remote auth does not use managed bitcoind

Cargo.lock, liana-gui/Cargo.toml, liana-gui/src/app/mod.rs, liana-gui/src/app/state/settings/bitcoind.rs, liana-gui/src/app/view/message.rs, liana-gui/src/app/view/settings.rs, liana-gui/src/help.rs, liana-gui/src/installer/message.rs, liana-gui/src/installer/mod.rs, liana-gui/src/installer/step/descriptor/editor/mod.rs, liana-gui/src/installer/view/mod.rs, liana-gui/src/lib.rs, liana-ui/src/component/button.rs, liana-ui/src/icon.rs, liana-ui/src/theme/button.rs, liana-ui/src/theme/palette.rs
=> feat: add links with info about changing backend or node type

liana-gui/src/app/cache.rs, liana-gui/src/app/message.rs, liana-gui/src/app/mod.rs, liana-gui/src/app/state/mod.rs, liana-gui/src/app/state/settings/bitcoind.rs, liana-gui/src/app/view/coins.rs, liana-gui/src/app/view/mod.rs, liana-gui/src/app/view/spend/mod.rs, liana-gui/src/gui/tab.rs, liana-gui/src/loader.rs
This PR is a preparatory step towards #1798.
If we want to cache values from different sources and update frequencies, e.g. when adding fiat prices, I think it will be convenient to group and update them independently of each other.
This PR adds a `DaemonCache` struct within `Cache` for storing and updating dynamic daemon values only.
The `UpdateDaemonCache` message replaces `UpdateCache` to update these daemon cache values only.
The new `CacheUpdated` message will be called when any fields within the cache have been updated, e.g. daemon values, fiat price values, etc.
=> refactor: update cache fields according to source

liana-gui/src/app/cache.rs, liana-gui/src/app/message.rs, liana-gui/src/app/mod.rs, liana-gui/src/gui/mod.rs, liana-gui/src/gui/pane.rs, liana-gui/src/gui/tab.rs
In order to reduce back pressure with multiple pane open, only one subscription is providing a tick every 1 second. It is up to each state of each panel to handle this tick.
For example the app state will compare the tick instant to the last time it had updated the daemon cache to know if it has to update it again.
=> Add global tick subscription

liana-gui/src/app/mod.rs, liana-gui/src/gui/mod.rs, liana-gui/src/gui/pane.rs, liana-gui/src/gui/tab.rs
This is a follow-up to #1834.
The tick parameter could be for an `Instant` in the past, e.g. if the GUI window is inactive for a while.
In the case of `DaemonCache`, storing `last_tick` would therefore not prevent multiple updates from a burst of tick messages.
The `on_tick()` methods should rather use `Instant::now()` for performing their logic.
=> fix: use Instant::now() in on_tick method

liana-gui/src/app/cache.rs, liana-gui/src/app/message.rs, liana-gui/src/app/mod.rs, liana-gui/src/app/state/mod.rs, liana-gui/src/app/state/settings/general.rs, liana-gui/src/app/wallet.rs, liana-gui/src/gui/cache.rs, liana-gui/src/gui/mod.rs, liana-gui/src/gui/pane.rs, liana-gui/src/gui/tab.rs, liana-gui/src/loader.rs
This PR addresses https://github.com/wizardsardine/liana/issues/1819 by adding a new global cache to store fiat prices.
The `GUI` rather than individual tabs will now take care of triggering new price requests and processing results .
=> store fiat prices in new global cache

liana-ui/src/component/badge.rs
Sometimes visibility of tooltip could be improved, what do you think?
With borders and background :
=> gui: fix badge's tooltip display

liana-gui/src/app/state/spend/step.rs, liana-gui/src/app/view/fiat.rs, liana-gui/src/app/view/spend/mod.rs, liana-gui/src/services/fiat/currency.rs
This allows to configure the number of decimals displayed per fiat currency.
=> configure number of decimals per fiat currency

liana-gui/src/node/bitcoind.rs, lianad/src/bitcoin/d/mod.rs
Sometimes liana-gui reads the previous bitcoin .cookie state before the new cookie is generated, it provokes an unauthorized error that is solved by waiting bitcoind startup before reading new cookie credentials.
close #1888
=> fix bitcoind start: retry on error 401

liana-gui/src/node/bitcoind.rs, lianad/src/bitcoin/d/mod.rs
backport of #1889 
Sometimes liana-gui reads the previous bitcoin .cookie state before the new cookie is generated, it provokes an unauthorized error that is solved by waiting bitcoind startup before reading new cookie credentials.
close #1888
=> backport: fix bitcoind start: retry on error 401
